-- Auto-generated product seed from src/data/products.ts
-- Idempotent: upsert by slug

INSERT INTO public.products (
  id, name, slug, sku, category_id, description, short_description,
  price, old_price, stock, images, features, specifications,
  rating, review_count, badge, discount_percent, is_active
) VALUES (
  '33333333-3333-3333-3333-000039d14f62',
  'Aquails DİJİTAL 304 PASLANMAZ ÇELİK MUSLUK',
  'dijital-304-paslanmaz-celik-musluk',
  '8409359155245',
  '11111111-1111-1111-1111-111111111108',
  'DİJİTAL 304 PASLANMAZ ÇELİK MUSLUK, 304 paslanmaz çelikten üretilmiş, su arıtma cihazlarına uygun estetik ve dayanıklı musluktur.',
  'DİJİTAL 304 PASLANMAZ ÇELİK MUSLUK, 304 paslanmaz çelikten üretilmiş, su arıtma cihazlarına uygun estetik ve dayanıklı m...',
  1250,
  NULL,
  10,
  '["/images/products/filtreler.jpg"]'::jsonb,
  '["304 paslanmaz çelik","Paslanmaya dayanıklı","Krom kaplama","Kolay montaj","Modern tasarım","5 yıl garanti"]'::jsonb,
  '{"Marka":"Aquails","Kategori":"Musluklar","Garanti":"5 Yıl"}'::jsonb,
  4.3,
  95,
  NULL,
  NULL,
  true
) ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  category_id = EXCLUDED.category_id,
  description = EXCLUDED.description,
  short_description = EXCLUDED.short_description,
  price = EXCLUDED.price,
  old_price = EXCLUDED.old_price,
  stock = EXCLUDED.stock,
  images = EXCLUDED.images,
  features = EXCLUDED.features,
  specifications = EXCLUDED.specifications,
  rating = EXCLUDED.rating,
  review_count = EXCLUDED.review_count,
  badge = EXCLUDED.badge,
  discount_percent = EXCLUDED.discount_percent,
  is_active = true;

INSERT INTO public.products (
  id, name, slug, sku, category_id, description, short_description,
  price, old_price, stock, images, features, specifications,
  rating, review_count, badge, discount_percent, is_active
) VALUES (
  '33333333-3333-3333-3333-00005dd60947',
  'PRO INLINE FİLTRELER',
  'pro-inline-filtreler',
  '8405941387309',
  '11111111-1111-1111-1111-111111111106',
  'PRO INLINE FİLTRELER, Aquails su arıtma cihazlarıyla tam uyumlu, NSF sertifikalı yüksek performanslı filtredir.',
  'PRO INLINE FİLTRELER, Aquails su arıtma cihazlarıyla tam uyumlu, NSF sertifikalı yüksek performanslı filtredir....',
  2499,
  2980,
  10,
  '["/images/products/dijital-su-aritma.jpg"]'::jsonb,
  '["NSF sertifikalı","6-12 ay ömür","Kolay değişim","Yüksek filtrasyon verimi","Güvenli paketleme","Aquails uyumlu"]'::jsonb,
  '{"Marka":"Aquails","Kategori":"Filtreler","Garanti":"2 Yıl"}'::jsonb,
  4.3,
  135,
  'discount',
  16,
  true
) ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  category_id = EXCLUDED.category_id,
  description = EXCLUDED.description,
  short_description = EXCLUDED.short_description,
  price = EXCLUDED.price,
  old_price = EXCLUDED.old_price,
  stock = EXCLUDED.stock,
  images = EXCLUDED.images,
  features = EXCLUDED.features,
  specifications = EXCLUDED.specifications,
  rating = EXCLUDED.rating,
  review_count = EXCLUDED.review_count,
  badge = EXCLUDED.badge,
  discount_percent = EXCLUDED.discount_percent,
  is_active = true;

INSERT INTO public.products (
  id, name, slug, sku, category_id, description, short_description,
  price, old_price, stock, images, features, specifications,
  rating, review_count, badge, discount_percent, is_active
) VALUES (
  '33333333-3333-3333-3333-000033bc7a68',
  'Aquails EONAQUA PRO DİJİTAL SU ARITMA CİHAZI',
  'aquails-eonaqua-pro-dijital-su-aritma-cihazi',
  '8404650131501',
  '11111111-1111-1111-1111-111111111103',
  'Aquails EONAQUA PRO DİJİTAL SU ARITMA CİHAZI, dijital TDS göstergesi ve akıllı filtre uyarı sistemi ile donatılmış modern su arıtma cihazıdır.',
  'Aquails EONAQUA PRO DİJİTAL SU ARITMA CİHAZI, dijital TDS göstergesi ve akıllı filtre uyarı sistemi ile donatılmış moder...',
  85900,
  NULL,
  10,
  '["/images/products/dijital-su-aritma.jpg"]'::jsonb,
  '["Dijital TDS göstergesi","Akıllı filtre uyarısı","7 aşamalı filtrasyon","Sessiz çalışma","LED ekran","5 yıl garanti"]'::jsonb,
  '{"Marka":"Aquails","Kategori":"Dijital Su Arıtma","Garanti":"5 Yıl"}'::jsonb,
  4.4,
  156,
  'new',
  NULL,
  true
) ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  category_id = EXCLUDED.category_id,
  description = EXCLUDED.description,
  short_description = EXCLUDED.short_description,
  price = EXCLUDED.price,
  old_price = EXCLUDED.old_price,
  stock = EXCLUDED.stock,
  images = EXCLUDED.images,
  features = EXCLUDED.features,
  specifications = EXCLUDED.specifications,
  rating = EXCLUDED.rating,
  review_count = EXCLUDED.review_count,
  badge = EXCLUDED.badge,
  discount_percent = EXCLUDED.discount_percent,
  is_active = true;

INSERT INTO public.products (
  id, name, slug, sku, category_id, description, short_description,
  price, old_price, stock, images, features, specifications,
  rating, review_count, badge, discount_percent, is_active
) VALUES (
  '33333333-3333-3333-3333-000058160578',
  'Aquails EONAQUA DİJİTAL SU ARITMA CİHAZI',
  'aquails-eonaqua-dijital-su-aritma-cihazi',
  '8371464896557',
  '11111111-1111-1111-1111-111111111103',
  'Aquails EONAQUA DİJİTAL SU ARITMA CİHAZI, dijital TDS göstergesi ve akıllı filtre uyarı sistemi ile donatılmış modern su arıtma cihazıdır.',
  'Aquails EONAQUA DİJİTAL SU ARITMA CİHAZI, dijital TDS göstergesi ve akıllı filtre uyarı sistemi ile donatılmış modern su...',
  65900,
  NULL,
  10,
  '["/images/products/direkt-akis-su-aritma.jpg"]'::jsonb,
  '["Dijital TDS göstergesi","Akıllı filtre uyarısı","7 aşamalı filtrasyon","Sessiz çalışma","LED ekran","5 yıl garanti"]'::jsonb,
  '{"Marka":"Aquails","Kategori":"Dijital Su Arıtma","Garanti":"5 Yıl"}'::jsonb,
  4.8,
  100,
  'premium',
  NULL,
  true
) ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  category_id = EXCLUDED.category_id,
  description = EXCLUDED.description,
  short_description = EXCLUDED.short_description,
  price = EXCLUDED.price,
  old_price = EXCLUDED.old_price,
  stock = EXCLUDED.stock,
  images = EXCLUDED.images,
  features = EXCLUDED.features,
  specifications = EXCLUDED.specifications,
  rating = EXCLUDED.rating,
  review_count = EXCLUDED.review_count,
  badge = EXCLUDED.badge,
  discount_percent = EXCLUDED.discount_percent,
  is_active = true;

INSERT INTO public.products (
  id, name, slug, sku, category_id, description, short_description,
  price, old_price, stock, images, features, specifications,
  rating, review_count, badge, discount_percent, is_active
) VALUES (
  '33333333-3333-3333-3333-00003e72356c',
  'Aquails BLUEDROP DİREK AKIŞ SU ARITMA CİHAZI',
  'aquails-bluedrop-direk-akis-su-aritma-cihazi',
  '8299605917741',
  '11111111-1111-1111-1111-111111111102',
  'Aquails BLUEDROP DİREK AKIŞ SU ARITMA CİHAZI, tank kullanmadan anında saf su üreten son nesil direkt akış su arıtma cihazıdır. Yüksek kapasite, düşük su atığı.',
  'Aquails BLUEDROP DİREK AKIŞ SU ARITMA CİHAZI, tank kullanmadan anında saf su üreten son nesil direkt akış su arıtma ciha...',
  95900,
  NULL,
  10,
  '["/images/products/ev-gerecleri.jpg"]'::jsonb,
  '["Tankless tasarım","Anında saf su","Günlük 600-800L kapasite","Otomatik yıkama","Düşük su atığı","5 yıl garanti"]'::jsonb,
  '{"Marka":"Aquails","Kategori":"Direkt Akış Su Arıtma","Garanti":"5 Yıl"}'::jsonb,
  4.4,
  68,
  'new',
  NULL,
  true
) ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  category_id = EXCLUDED.category_id,
  description = EXCLUDED.description,
  short_description = EXCLUDED.short_description,
  price = EXCLUDED.price,
  old_price = EXCLUDED.old_price,
  stock = EXCLUDED.stock,
  images = EXCLUDED.images,
  features = EXCLUDED.features,
  specifications = EXCLUDED.specifications,
  rating = EXCLUDED.rating,
  review_count = EXCLUDED.review_count,
  badge = EXCLUDED.badge,
  discount_percent = EXCLUDED.discount_percent,
  is_active = true;

INSERT INTO public.products (
  id, name, slug, sku, category_id, description, short_description,
  price, old_price, stock, images, features, specifications,
  rating, review_count, badge, discount_percent, is_active
) VALUES (
  '33333333-3333-3333-3333-0000642eb0bd',
  'Aquails Diamond Döküm 7 Parça Tencere Seti (Cam Kapaklı)',
  'aquails-diamond-dokum-7-parca-tencere-seti-cam-kapakli',
  '8352917848109',
  '11111111-1111-1111-1111-111111111113',
  'Aquails Diamond Döküm 7 Parça Tencere Seti (Cam Kapaklı), mutfağınızda kalite ve şıklığı bir araya getiren dayanıklı ev gerecidir.',
  'Aquails Diamond Döküm 7 Parça Tencere Seti (Cam Kapaklı), mutfağınızda kalite ve şıklığı bir araya getiren dayanıklı ev ...',
  22800,
  NULL,
  10,
  '["/images/products/bina-girisi-filtrasyon.jpg"]'::jsonb,
  '["Dayanıklı döküm/granit","PFOA içermez","Kolay temizlik","Isıya dayanıklı","Şık tasarım","2 yıl garanti"]'::jsonb,
  '{"Marka":"Aquails","Kategori":"Ev Gereçleri","Garanti":"2 Yıl"}'::jsonb,
  4.7,
  55,
  NULL,
  NULL,
  true
) ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  category_id = EXCLUDED.category_id,
  description = EXCLUDED.description,
  short_description = EXCLUDED.short_description,
  price = EXCLUDED.price,
  old_price = EXCLUDED.old_price,
  stock = EXCLUDED.stock,
  images = EXCLUDED.images,
  features = EXCLUDED.features,
  specifications = EXCLUDED.specifications,
  rating = EXCLUDED.rating,
  review_count = EXCLUDED.review_count,
  badge = EXCLUDED.badge,
  discount_percent = EXCLUDED.discount_percent,
  is_active = true;

INSERT INTO public.products (
  id, name, slug, sku, category_id, description, short_description,
  price, old_price, stock, images, features, specifications,
  rating, review_count, badge, discount_percent, is_active
) VALUES (
  '33333333-3333-3333-3333-000045c07725',
  'Aquails TRİO CLEAN 10" 3 LÜ BİNA GİRİŞ FİLTRASYON ARITMA SİSTEMİ',
  'aquails-trio-clean-10-3-lu-bina-giris-filtrasyon-aritma-sistemi',
  '8335644983341',
  '11111111-1111-1111-1111-111111111105',
  'Aquails TRİO CLEAN 10" 3 LÜ BİNA GİRİŞ FİLTRASYON ARITMA SİSTEMİ, apartman ve site girişlerinde kullanılan profesyonel ön filtrasyon sistemidir.',
  'Aquails TRİO CLEAN 10" 3 LÜ BİNA GİRİŞ FİLTRASYON ARITMA SİSTEMİ, apartman ve site girişlerinde kullanılan profesyonel ö...',
  49900,
  55900,
  10,
  '["/images/products/ev-gerecleri.jpg"]'::jsonb,
  '["20 inç jumbo filtreler","Paslanmaz çelik başlık","Yüksek debi","Kolay filtre değişimi","Paslanmaz bağlantı","2 yıl garanti"]'::jsonb,
  '{"Marka":"Aquails","Kategori":"Bina Girişi Filtrasyon","Garanti":"2 Yıl","Aşama Sayısı":"3 Aşama"}'::jsonb,
  4.3,
  81,
  'discount',
  11,
  true
) ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  category_id = EXCLUDED.category_id,
  description = EXCLUDED.description,
  short_description = EXCLUDED.short_description,
  price = EXCLUDED.price,
  old_price = EXCLUDED.old_price,
  stock = EXCLUDED.stock,
  images = EXCLUDED.images,
  features = EXCLUDED.features,
  specifications = EXCLUDED.specifications,
  rating = EXCLUDED.rating,
  review_count = EXCLUDED.review_count,
  badge = EXCLUDED.badge,
  discount_percent = EXCLUDED.discount_percent,
  is_active = true;

INSERT INTO public.products (
  id, name, slug, sku, category_id, description, short_description,
  price, old_price, stock, images, features, specifications,
  rating, review_count, badge, discount_percent, is_active
) VALUES (
  '33333333-3333-3333-3333-00005f2948e0',
  '47 PARÇA ÇATAL KAŞIK BIÇAK TAKIMI',
  '47-parca-catal-kasik-bicak-takimi',
  '8052755136557',
  '11111111-1111-1111-1111-111111111113',
  '47 PARÇA ÇATAL KAŞIK BIÇAK TAKIMI, mutfağınızda kalite ve şıklığı bir araya getiren dayanıklı ev gerecidir.',
  '47 PARÇA ÇATAL KAŞIK BIÇAK TAKIMI, mutfağınızda kalite ve şıklığı bir araya getiren dayanıklı ev gerecidir....',
  24290,
  NULL,
  10,
  '["/images/products/bina-girisi-filtrasyon.jpg"]'::jsonb,
  '["Dayanıklı döküm/granit","PFOA içermez","Kolay temizlik","Isıya dayanıklı","Şık tasarım","2 yıl garanti"]'::jsonb,
  '{"Marka":"Aquails","Kategori":"Ev Gereçleri","Garanti":"2 Yıl"}'::jsonb,
  4.8,
  98,
  NULL,
  NULL,
  true
) ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  category_id = EXCLUDED.category_id,
  description = EXCLUDED.description,
  short_description = EXCLUDED.short_description,
  price = EXCLUDED.price,
  old_price = EXCLUDED.old_price,
  stock = EXCLUDED.stock,
  images = EXCLUDED.images,
  features = EXCLUDED.features,
  specifications = EXCLUDED.specifications,
  rating = EXCLUDED.rating,
  review_count = EXCLUDED.review_count,
  badge = EXCLUDED.badge,
  discount_percent = EXCLUDED.discount_percent,
  is_active = true;

INSERT INTO public.products (
  id, name, slug, sku, category_id, description, short_description,
  price, old_price, stock, images, features, specifications,
  rating, review_count, badge, discount_percent, is_active
) VALUES (
  '33333333-3333-3333-3333-00006cde973a',
  'Aquails DAİRE GİRİŞİ 10'''' FİLTRASYON SİSTEMİ',
  'daire-girisi-10-filtrasyon-sistemi',
  '8272879353901',
  '11111111-1111-1111-1111-111111111105',
  'DAİRE GİRİŞİ 10'''' FİLTRASYON SİSTEMİ, apartman ve site girişlerinde kullanılan profesyonel ön filtrasyon sistemidir.',
  'DAİRE GİRİŞİ 10'''' FİLTRASYON SİSTEMİ, apartman ve site girişlerinde kullanılan profesyonel ön filtrasyon sistemidir....',
  3349,
  NULL,
  10,
  '["/images/products/filtreler.jpg"]'::jsonb,
  '["20 inç jumbo filtreler","Paslanmaz çelik başlık","Yüksek debi","Kolay filtre değişimi","Paslanmaz bağlantı","2 yıl garanti"]'::jsonb,
  '{"Marka":"Aquails","Kategori":"Bina Girişi Filtrasyon","Garanti":"2 Yıl"}'::jsonb,
  4.6,
  136,
  NULL,
  NULL,
  true
) ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  category_id = EXCLUDED.category_id,
  description = EXCLUDED.description,
  short_description = EXCLUDED.short_description,
  price = EXCLUDED.price,
  old_price = EXCLUDED.old_price,
  stock = EXCLUDED.stock,
  images = EXCLUDED.images,
  features = EXCLUDED.features,
  specifications = EXCLUDED.specifications,
  rating = EXCLUDED.rating,
  review_count = EXCLUDED.review_count,
  badge = EXCLUDED.badge,
  discount_percent = EXCLUDED.discount_percent,
  is_active = true;

INSERT INTO public.products (
  id, name, slug, sku, category_id, description, short_description,
  price, old_price, stock, images, features, specifications,
  rating, review_count, badge, discount_percent, is_active
) VALUES (
  '33333333-3333-3333-3333-00004f9159a2',
  'Aquails SU ARITMA CİHAZI UYUMLU 5Lİ FİLTRE SET',
  'aquails-su-aritma-cihazi-uyumlu-5li-filtre-set',
  '8229289820205',
  '11111111-1111-1111-1111-111111111106',
  'Aquails SU ARITMA CİHAZI UYUMLU 5Lİ FİLTRE SET, Aquails su arıtma cihazlarıyla tam uyumlu, NSF sertifikalı yüksek performanslı filtredir.',
  'Aquails SU ARITMA CİHAZI UYUMLU 5Lİ FİLTRE SET, Aquails su arıtma cihazlarıyla tam uyumlu, NSF sertifikalı yüksek perfor...',
  2475,
  2500,
  10,
  '["/images/products/dijital-su-aritma.jpg"]'::jsonb,
  '["NSF sertifikalı","6-12 ay ömür","Kolay değişim","Yüksek filtrasyon verimi","Güvenli paketleme","Aquails uyumlu"]'::jsonb,
  '{"Marka":"Aquails","Kategori":"Filtreler","Garanti":"2 Yıl"}'::jsonb,
  4.3,
  77,
  'discount',
  1,
  true
) ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  category_id = EXCLUDED.category_id,
  description = EXCLUDED.description,
  short_description = EXCLUDED.short_description,
  price = EXCLUDED.price,
  old_price = EXCLUDED.old_price,
  stock = EXCLUDED.stock,
  images = EXCLUDED.images,
  features = EXCLUDED.features,
  specifications = EXCLUDED.specifications,
  rating = EXCLUDED.rating,
  review_count = EXCLUDED.review_count,
  badge = EXCLUDED.badge,
  discount_percent = EXCLUDED.discount_percent,
  is_active = true;

INSERT INTO public.products (
  id, name, slug, sku, category_id, description, short_description,
  price, old_price, stock, images, features, specifications,
  rating, review_count, badge, discount_percent, is_active
) VALUES (
  '33333333-3333-3333-3333-000053d90922',
  'Aquails H2O GREEN PLUS DİJİTAL SU ARITMA SİSTEMİ',
  'aquails-h2o-green-plus-dijital-su-aritma-sistemi',
  '8157080748077',
  '11111111-1111-1111-1111-111111111103',
  'Aquails H2O GREEN PLUS DİJİTAL SU ARITMA SİSTEMİ, dijital TDS göstergesi ve akıllı filtre uyarı sistemi ile donatılmış modern su arıtma cihazıdır.',
  'Aquails H2O GREEN PLUS DİJİTAL SU ARITMA SİSTEMİ, dijital TDS göstergesi ve akıllı filtre uyarı sistemi ile donatılmış m...',
  35800,
  37900,
  10,
  '["/images/products/filtreler.jpg"]'::jsonb,
  '["Dijital TDS göstergesi","Akıllı filtre uyarısı","7 aşamalı filtrasyon","Sessiz çalışma","LED ekran","5 yıl garanti"]'::jsonb,
  '{"Marka":"Aquails","Kategori":"Dijital Su Arıtma","Garanti":"5 Yıl"}'::jsonb,
  4.2,
  144,
  'discount',
  6,
  true
) ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  category_id = EXCLUDED.category_id,
  description = EXCLUDED.description,
  short_description = EXCLUDED.short_description,
  price = EXCLUDED.price,
  old_price = EXCLUDED.old_price,
  stock = EXCLUDED.stock,
  images = EXCLUDED.images,
  features = EXCLUDED.features,
  specifications = EXCLUDED.specifications,
  rating = EXCLUDED.rating,
  review_count = EXCLUDED.review_count,
  badge = EXCLUDED.badge,
  discount_percent = EXCLUDED.discount_percent,
  is_active = true;

INSERT INTO public.products (
  id, name, slug, sku, category_id, description, short_description,
  price, old_price, stock, images, features, specifications,
  rating, review_count, badge, discount_percent, is_active
) VALUES (
  '33333333-3333-3333-3333-00002b70c8c3',
  'Aquails ALKALİNE FİLTRE',
  'aquails-alkaline-filtre',
  '8121664798765',
  '11111111-1111-1111-1111-111111111106',
  'Aquails ALKALİNE FİLTRE, Aquails su arıtma cihazlarıyla tam uyumlu, NSF sertifikalı yüksek performanslı filtredir.',
  'Aquails ALKALİNE FİLTRE, Aquails su arıtma cihazlarıyla tam uyumlu, NSF sertifikalı yüksek performanslı filtredir....',
  3359,
  NULL,
  10,
  '["/images/products/filtreler.jpg"]'::jsonb,
  '["NSF sertifikalı","6-12 ay ömür","Kolay değişim","Yüksek filtrasyon verimi","Güvenli paketleme","Aquails uyumlu"]'::jsonb,
  '{"Marka":"Aquails","Kategori":"Filtreler","Garanti":"2 Yıl"}'::jsonb,
  4.2,
  26,
  NULL,
  NULL,
  true
) ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  category_id = EXCLUDED.category_id,
  description = EXCLUDED.description,
  short_description = EXCLUDED.short_description,
  price = EXCLUDED.price,
  old_price = EXCLUDED.old_price,
  stock = EXCLUDED.stock,
  images = EXCLUDED.images,
  features = EXCLUDED.features,
  specifications = EXCLUDED.specifications,
  rating = EXCLUDED.rating,
  review_count = EXCLUDED.review_count,
  badge = EXCLUDED.badge,
  discount_percent = EXCLUDED.discount_percent,
  is_active = true;

INSERT INTO public.products (
  id, name, slug, sku, category_id, description, short_description,
  price, old_price, stock, images, features, specifications,
  rating, review_count, badge, discount_percent, is_active
) VALUES (
  '33333333-3333-3333-3333-000051591a2f',
  'Aquails MİNERAL PH STABİLİZER FİLTRE',
  'aquails-mineral-ph-stabilizer-filtre',
  '8121666830381',
  '11111111-1111-1111-1111-111111111106',
  'Aquails MİNERAL PH STABİLİZER FİLTRE, Aquails su arıtma cihazlarıyla tam uyumlu, NSF sertifikalı yüksek performanslı filtredir.',
  'Aquails MİNERAL PH STABİLİZER FİLTRE, Aquails su arıtma cihazlarıyla tam uyumlu, NSF sertifikalı yüksek performanslı fil...',
  3460,
  NULL,
  10,
  '["/images/products/filtreler.jpg"]'::jsonb,
  '["NSF sertifikalı","6-12 ay ömür","Kolay değişim","Yüksek filtrasyon verimi","Güvenli paketleme","Aquails uyumlu"]'::jsonb,
  '{"Marka":"Aquails","Kategori":"Filtreler","Garanti":"2 Yıl"}'::jsonb,
  4.8,
  14,
  NULL,
  NULL,
  true
) ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  category_id = EXCLUDED.category_id,
  description = EXCLUDED.description,
  short_description = EXCLUDED.short_description,
  price = EXCLUDED.price,
  old_price = EXCLUDED.old_price,
  stock = EXCLUDED.stock,
  images = EXCLUDED.images,
  features = EXCLUDED.features,
  specifications = EXCLUDED.specifications,
  rating = EXCLUDED.rating,
  review_count = EXCLUDED.review_count,
  badge = EXCLUDED.badge,
  discount_percent = EXCLUDED.discount_percent,
  is_active = true;

INSERT INTO public.products (
  id, name, slug, sku, category_id, description, short_description,
  price, old_price, stock, images, features, specifications,
  rating, review_count, badge, discount_percent, is_active
) VALUES (
  '33333333-3333-3333-3333-0000242ea830',
  'Aquails ANTİOXDANT ORP ALKALİNE FİLTRE',
  'aquails-antioxdant-orp-alkaline-filtre',
  '8121668763693',
  '11111111-1111-1111-1111-111111111106',
  'Aquails ANTİOXDANT ORP ALKALİNE FİLTRE, Aquails su arıtma cihazlarıyla tam uyumlu, NSF sertifikalı yüksek performanslı filtredir.',
  'Aquails ANTİOXDANT ORP ALKALİNE FİLTRE, Aquails su arıtma cihazlarıyla tam uyumlu, NSF sertifikalı yüksek performanslı f...',
  3549,
  NULL,
  10,
  '["/images/products/bina-girisi-filtrasyon.jpg"]'::jsonb,
  '["NSF sertifikalı","6-12 ay ömür","Kolay değişim","Yüksek filtrasyon verimi","Güvenli paketleme","Aquails uyumlu"]'::jsonb,
  '{"Marka":"Aquails","Kategori":"Filtreler","Garanti":"2 Yıl"}'::jsonb,
  4.2,
  150,
  NULL,
  NULL,
  true
) ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  category_id = EXCLUDED.category_id,
  description = EXCLUDED.description,
  short_description = EXCLUDED.short_description,
  price = EXCLUDED.price,
  old_price = EXCLUDED.old_price,
  stock = EXCLUDED.stock,
  images = EXCLUDED.images,
  features = EXCLUDED.features,
  specifications = EXCLUDED.specifications,
  rating = EXCLUDED.rating,
  review_count = EXCLUDED.review_count,
  badge = EXCLUDED.badge,
  discount_percent = EXCLUDED.discount_percent,
  is_active = true;

INSERT INTO public.products (
  id, name, slug, sku, category_id, description, short_description,
  price, old_price, stock, images, features, specifications,
  rating, review_count, badge, discount_percent, is_active
) VALUES (
  '33333333-3333-3333-3333-0000273e6049',
  'Aquails 20" 3 LÜ BİNA GİRİŞ FİLTRASYON ARITMA SİSTEMİ',
  'aquails-20-3-lu-bina-giris-filtrasyon-aritma-sistemi',
  '8103853850669',
  '11111111-1111-1111-1111-111111111105',
  'Aquails 20" 3 LÜ BİNA GİRİŞ FİLTRASYON ARITMA SİSTEMİ, apartman ve site girişlerinde kullanılan profesyonel ön filtrasyon sistemidir.',
  'Aquails 20" 3 LÜ BİNA GİRİŞ FİLTRASYON ARITMA SİSTEMİ, apartman ve site girişlerinde kullanılan profesyonel ön filtrasyo...',
  29990,
  NULL,
  10,
  '["/images/products/filtreler.jpg"]'::jsonb,
  '["20 inç jumbo filtreler","Paslanmaz çelik başlık","Yüksek debi","Kolay filtre değişimi","Paslanmaz bağlantı","2 yıl garanti"]'::jsonb,
  '{"Marka":"Aquails","Kategori":"Bina Girişi Filtrasyon","Garanti":"2 Yıl","Aşama Sayısı":"3 Aşama"}'::jsonb,
  4.3,
  83,
  NULL,
  NULL,
  true
) ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  category_id = EXCLUDED.category_id,
  description = EXCLUDED.description,
  short_description = EXCLUDED.short_description,
  price = EXCLUDED.price,
  old_price = EXCLUDED.old_price,
  stock = EXCLUDED.stock,
  images = EXCLUDED.images,
  features = EXCLUDED.features,
  specifications = EXCLUDED.specifications,
  rating = EXCLUDED.rating,
  review_count = EXCLUDED.review_count,
  badge = EXCLUDED.badge,
  discount_percent = EXCLUDED.discount_percent,
  is_active = true;

INSERT INTO public.products (
  id, name, slug, sku, category_id, description, short_description,
  price, old_price, stock, images, features, specifications,
  rating, review_count, badge, discount_percent, is_active
) VALUES (
  '33333333-3333-3333-3333-00007c5b3029',
  'Aquails ORP FİLTRE',
  'aquails-orp-filtre',
  '8103178764333',
  '11111111-1111-1111-1111-111111111106',
  'Aquails ORP FİLTRE, Aquails su arıtma cihazlarıyla tam uyumlu, NSF sertifikalı yüksek performanslı filtredir.',
  'Aquails ORP FİLTRE, Aquails su arıtma cihazlarıyla tam uyumlu, NSF sertifikalı yüksek performanslı filtredir....',
  3751,
  NULL,
  10,
  '["/images/products/filtreler.jpg"]'::jsonb,
  '["NSF sertifikalı","6-12 ay ömür","Kolay değişim","Yüksek filtrasyon verimi","Güvenli paketleme","Aquails uyumlu"]'::jsonb,
  '{"Marka":"Aquails","Kategori":"Filtreler","Garanti":"2 Yıl"}'::jsonb,
  4.3,
  105,
  NULL,
  NULL,
  true
) ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  category_id = EXCLUDED.category_id,
  description = EXCLUDED.description,
  short_description = EXCLUDED.short_description,
  price = EXCLUDED.price,
  old_price = EXCLUDED.old_price,
  stock = EXCLUDED.stock,
  images = EXCLUDED.images,
  features = EXCLUDED.features,
  specifications = EXCLUDED.specifications,
  rating = EXCLUDED.rating,
  review_count = EXCLUDED.review_count,
  badge = EXCLUDED.badge,
  discount_percent = EXCLUDED.discount_percent,
  is_active = true;

INSERT INTO public.products (
  id, name, slug, sku, category_id, description, short_description,
  price, old_price, stock, images, features, specifications,
  rating, review_count, badge, discount_percent, is_active
) VALUES (
  '33333333-3333-3333-3333-00001da702f0',
  'ALKALİ MİNERAL FİLTRE',
  'alkali-mineral-filtre',
  '8103165788205',
  '11111111-1111-1111-1111-111111111106',
  'ALKALİ MİNERAL FİLTRE, Aquails su arıtma cihazlarıyla tam uyumlu, NSF sertifikalı yüksek performanslı filtredir.',
  'ALKALİ MİNERAL FİLTRE, Aquails su arıtma cihazlarıyla tam uyumlu, NSF sertifikalı yüksek performanslı filtredir....',
  2519,
  NULL,
  10,
  '["/images/products/filtreler.jpg"]'::jsonb,
  '["NSF sertifikalı","6-12 ay ömür","Kolay değişim","Yüksek filtrasyon verimi","Güvenli paketleme","Aquails uyumlu"]'::jsonb,
  '{"Marka":"Aquails","Kategori":"Filtreler","Garanti":"2 Yıl"}'::jsonb,
  4.4,
  22,
  NULL,
  NULL,
  true
) ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  category_id = EXCLUDED.category_id,
  description = EXCLUDED.description,
  short_description = EXCLUDED.short_description,
  price = EXCLUDED.price,
  old_price = EXCLUDED.old_price,
  stock = EXCLUDED.stock,
  images = EXCLUDED.images,
  features = EXCLUDED.features,
  specifications = EXCLUDED.specifications,
  rating = EXCLUDED.rating,
  review_count = EXCLUDED.review_count,
  badge = EXCLUDED.badge,
  discount_percent = EXCLUDED.discount_percent,
  is_active = true;

INSERT INTO public.products (
  id, name, slug, sku, category_id, description, short_description,
  price, old_price, stock, images, features, specifications,
  rating, review_count, badge, discount_percent, is_active
) VALUES (
  '33333333-3333-3333-3333-0000346a1641',
  'Aquails H2O TESLA (ALKALİ) SU ARITMA SİSTEMİ / 6 AŞAMA',
  'aquails-h2o-tesla-alkali-su-aritma-sistemi-6-asama',
  '8063948423213',
  '11111111-1111-1111-1111-111111111106',
  'Aquails H2O TESLA (ALKALİ) SU ARITMA SİSTEMİ / 6 AŞAMA, Aquails su arıtma cihazlarıyla tam uyumlu, NSF sertifikalı yüksek performanslı filtredir.',
  'Aquails H2O TESLA (ALKALİ) SU ARITMA SİSTEMİ / 6 AŞAMA, Aquails su arıtma cihazlarıyla tam uyumlu, NSF sertifikalı yükse...',
  55000,
  65000,
  10,
  '["/images/products/sebiller.jpg"]'::jsonb,
  '["NSF sertifikalı","6-12 ay ömür","Kolay değişim","Yüksek filtrasyon verimi","Güvenli paketleme","Aquails uyumlu"]'::jsonb,
  '{"Marka":"Aquails","Kategori":"Filtreler","Garanti":"2 Yıl","Aşama Sayısı":"6 Aşama"}'::jsonb,
  4.8,
  120,
  'discount',
  15,
  true
) ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  category_id = EXCLUDED.category_id,
  description = EXCLUDED.description,
  short_description = EXCLUDED.short_description,
  price = EXCLUDED.price,
  old_price = EXCLUDED.old_price,
  stock = EXCLUDED.stock,
  images = EXCLUDED.images,
  features = EXCLUDED.features,
  specifications = EXCLUDED.specifications,
  rating = EXCLUDED.rating,
  review_count = EXCLUDED.review_count,
  badge = EXCLUDED.badge,
  discount_percent = EXCLUDED.discount_percent,
  is_active = true;

INSERT INTO public.products (
  id, name, slug, sku, category_id, description, short_description,
  price, old_price, stock, images, features, specifications,
  rating, review_count, badge, discount_percent, is_active
) VALUES (
  '33333333-3333-3333-3333-00000cdddc7b',
  'Aquails OR-351 ARITMALI SEBİL',
  'or-351-aritmali-sebil',
  '8090262011949',
  '11111111-1111-1111-1111-111111111104',
  'OR-351 ARITMALI SEBİL, sıcak ve soğuk su seçenekleriyle ofis ve ev kullanımına uygun arıtmalı sebil sistemidir.',
  'OR-351 ARITMALI SEBİL, sıcak ve soğuk su seçenekleriyle ofis ve ev kullanımına uygun arıtmalı sebil sistemidir....',
  112000,
  NULL,
  10,
  '["/images/products/ev-temizligi.jpg"]'::jsonb,
  '["Sıcak & soğuk su","Arıtmalı sistem","Enerji tasarrufu","Çocuk güvenlik kilidi","Geniş su haznesi","2 yıl garanti"]'::jsonb,
  '{"Marka":"Aquails","Kategori":"Sebiller","Garanti":"2 Yıl"}'::jsonb,
  4.6,
  28,
  NULL,
  NULL,
  true
) ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  category_id = EXCLUDED.category_id,
  description = EXCLUDED.description,
  short_description = EXCLUDED.short_description,
  price = EXCLUDED.price,
  old_price = EXCLUDED.old_price,
  stock = EXCLUDED.stock,
  images = EXCLUDED.images,
  features = EXCLUDED.features,
  specifications = EXCLUDED.specifications,
  rating = EXCLUDED.rating,
  review_count = EXCLUDED.review_count,
  badge = EXCLUDED.badge,
  discount_percent = EXCLUDED.discount_percent,
  is_active = true;

INSERT INTO public.products (
  id, name, slug, sku, category_id, description, short_description,
  price, old_price, stock, images, features, specifications,
  rating, review_count, badge, discount_percent, is_active
) VALUES (
  '33333333-3333-3333-3333-0000162b7d6a',
  'Aquails ROBOTİX TEMİZLİK ROBOTU',
  'aquails-robotix-temizlik-robotu',
  '8089602687021',
  '11111111-1111-1111-1111-111111111112',
  'Aquails ROBOTİX TEMİZLİK ROBOTU, evinizi hijyenik tutmanızı sağlayan güçlü performanslı temizlik ürünüdür.',
  'Aquails ROBOTİX TEMİZLİK ROBOTU, evinizi hijyenik tutmanızı sağlayan güçlü performanslı temizlik ürünüdür....',
  118900,
  NULL,
  10,
  '["/images/products/elektrikli-ev-aletleri.jpg"]'::jsonb,
  '["Güçlü emiş","HEPA filtre","Enerji verimli","Sessiz çalışma","Kolay temizlik","2 yıl garanti"]'::jsonb,
  '{"Marka":"Aquails","Kategori":"Ev Temizliği","Garanti":"2 Yıl"}'::jsonb,
  4.2,
  158,
  NULL,
  NULL,
  true
) ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  category_id = EXCLUDED.category_id,
  description = EXCLUDED.description,
  short_description = EXCLUDED.short_description,
  price = EXCLUDED.price,
  old_price = EXCLUDED.old_price,
  stock = EXCLUDED.stock,
  images = EXCLUDED.images,
  features = EXCLUDED.features,
  specifications = EXCLUDED.specifications,
  rating = EXCLUDED.rating,
  review_count = EXCLUDED.review_count,
  badge = EXCLUDED.badge,
  discount_percent = EXCLUDED.discount_percent,
  is_active = true;

INSERT INTO public.products (
  id, name, slug, sku, category_id, description, short_description,
  price, old_price, stock, images, features, specifications,
  rating, review_count, badge, discount_percent, is_active
) VALUES (
  '33333333-3333-3333-3333-000019ae2263',
  'KIYMA MAKİNESİ',
  'kiyma-makinesi',
  '8087497932845',
  '11111111-1111-1111-1111-111111111111',
  'KIYMA MAKİNESİ, mutfak işlerinizi kolaylaştıran güçlü ve enerji verimli elektrikli ev aletidir.',
  'KIYMA MAKİNESİ, mutfak işlerinizi kolaylaştıran güçlü ve enerji verimli elektrikli ev aletidir....',
  21600,
  NULL,
  10,
  '["/images/products/su-aritma-cihazlari.jpg"]'::jsonb,
  '["Güçlü motor","Enerji verimli","Paslanmaz çelik bıçaklar","Kolay temizlik","Güvenlik kilidi","2 yıl garanti"]'::jsonb,
  '{"Marka":"Aquails","Kategori":"Elektrikli Ev Aletleri","Garanti":"2 Yıl"}'::jsonb,
  4.8,
  146,
  NULL,
  NULL,
  true
) ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  category_id = EXCLUDED.category_id,
  description = EXCLUDED.description,
  short_description = EXCLUDED.short_description,
  price = EXCLUDED.price,
  old_price = EXCLUDED.old_price,
  stock = EXCLUDED.stock,
  images = EXCLUDED.images,
  features = EXCLUDED.features,
  specifications = EXCLUDED.specifications,
  rating = EXCLUDED.rating,
  review_count = EXCLUDED.review_count,
  badge = EXCLUDED.badge,
  discount_percent = EXCLUDED.discount_percent,
  is_active = true;

INSERT INTO public.products (
  id, name, slug, sku, category_id, description, short_description,
  price, old_price, stock, images, features, specifications,
  rating, review_count, badge, discount_percent, is_active
) VALUES (
  '33333333-3333-3333-3333-0000442b223b',
  'Aquails EKO PLUS  SU ARITMA',
  'aquails-eko-plus-su-aritma',
  '8065692598317',
  '11111111-1111-1111-1111-111111111101',
  'Aquails EKO PLUS  SU ARITMA, 7 aşamalı Reverse Osmosis teknolojisi ile musluk suyunuzu en saf hale getiren premium su arıtma sistemidir. %99.9 arıtma performansı.',
  'Aquails EKO PLUS  SU ARITMA, 7 aşamalı Reverse Osmosis teknolojisi ile musluk suyunuzu en saf hale getiren premium su ar...',
  18900,
  NULL,
  10,
  '["/images/products/pompa-ve-yedek-parcalar.jpg"]'::jsonb,
  '["7 aşamalı filtrasyon","Günlük 189L su üretimi","Paslanmaz çelik tank","Enerji verimli","Kolay kurulum","5 yıl garanti"]'::jsonb,
  '{"Marka":"Aquails","Kategori":"Su Arıtma Cihazları","Garanti":"5 Yıl"}'::jsonb,
  4.9,
  99,
  NULL,
  NULL,
  true
) ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  category_id = EXCLUDED.category_id,
  description = EXCLUDED.description,
  short_description = EXCLUDED.short_description,
  price = EXCLUDED.price,
  old_price = EXCLUDED.old_price,
  stock = EXCLUDED.stock,
  images = EXCLUDED.images,
  features = EXCLUDED.features,
  specifications = EXCLUDED.specifications,
  rating = EXCLUDED.rating,
  review_count = EXCLUDED.review_count,
  badge = EXCLUDED.badge,
  discount_percent = EXCLUDED.discount_percent,
  is_active = true;

INSERT INTO public.products (
  id, name, slug, sku, category_id, description, short_description,
  price, old_price, stock, images, features, specifications,
  rating, review_count, badge, discount_percent, is_active
) VALUES (
  '33333333-3333-3333-3333-00004fec288e',
  'Aquails Pompa Seti',
  'aquails-pompa-seti',
  '8063942492205',
  '11111111-1111-1111-1111-111111111109',
  'Aquails Pompa Seti, su arıtma cihazlarınızın bakımı için gerekli orijinal yedek parçadır.',
  'Aquails Pompa Seti, su arıtma cihazlarınızın bakımı için gerekli orijinal yedek parçadır....',
  4490,
  NULL,
  10,
  '["/images/products/musluklar.jpg"]'::jsonb,
  '["Orijinal yedek parça","Kolay kurulum","Uzun ömürlü","Uygun fiyat","Hızlı teslimat","1 yıl garanti"]'::jsonb,
  '{"Marka":"Aquails","Kategori":"Pompa ve Yedek Parçalar","Garanti":"2 Yıl"}'::jsonb,
  4.9,
  61,
  NULL,
  NULL,
  true
) ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  category_id = EXCLUDED.category_id,
  description = EXCLUDED.description,
  short_description = EXCLUDED.short_description,
  price = EXCLUDED.price,
  old_price = EXCLUDED.old_price,
  stock = EXCLUDED.stock,
  images = EXCLUDED.images,
  features = EXCLUDED.features,
  specifications = EXCLUDED.specifications,
  rating = EXCLUDED.rating,
  review_count = EXCLUDED.review_count,
  badge = EXCLUDED.badge,
  discount_percent = EXCLUDED.discount_percent,
  is_active = true;

INSERT INTO public.products (
  id, name, slug, sku, category_id, description, short_description,
  price, old_price, stock, images, features, specifications,
  rating, review_count, badge, discount_percent, is_active
) VALUES (
  '33333333-3333-3333-3333-0000501d03d4',
  'Aquails 304 PASLANMAZ ÇELİK MUSLUK',
  '304-paslanmaz-celik-musluk',
  '8059496038445',
  '11111111-1111-1111-1111-111111111108',
  '304 PASLANMAZ ÇELİK MUSLUK, 304 paslanmaz çelikten üretilmiş, su arıtma cihazlarına uygun estetik ve dayanıklı musluktur.',
  '304 PASLANMAZ ÇELİK MUSLUK, 304 paslanmaz çelikten üretilmiş, su arıtma cihazlarına uygun estetik ve dayanıklı musluktur...',
  2899,
  NULL,
  10,
  '["/images/products/tens-cihazi.jpg"]'::jsonb,
  '["304 paslanmaz çelik","Paslanmaya dayanıklı","Krom kaplama","Kolay montaj","Modern tasarım","5 yıl garanti"]'::jsonb,
  '{"Marka":"Aquails","Kategori":"Musluklar","Garanti":"5 Yıl"}'::jsonb,
  4.3,
  11,
  NULL,
  NULL,
  true
) ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  category_id = EXCLUDED.category_id,
  description = EXCLUDED.description,
  short_description = EXCLUDED.short_description,
  price = EXCLUDED.price,
  old_price = EXCLUDED.old_price,
  stock = EXCLUDED.stock,
  images = EXCLUDED.images,
  features = EXCLUDED.features,
  specifications = EXCLUDED.specifications,
  rating = EXCLUDED.rating,
  review_count = EXCLUDED.review_count,
  badge = EXCLUDED.badge,
  discount_percent = EXCLUDED.discount_percent,
  is_active = true;

INSERT INTO public.products (
  id, name, slug, sku, category_id, description, short_description,
  price, old_price, stock, images, features, specifications,
  rating, review_count, badge, discount_percent, is_active
) VALUES (
  '33333333-3333-3333-3333-0000338a1105',
  'Tens Cihazı',
  'tens-cihazi',
  '8055185080365',
  '11111111-1111-1111-1111-111111111114',
  'Tens Cihazı, fiziksel rahatsızlıkları hafifletmek için tasarlanmış profesyonel TENS/EMS cihazıdır.',
  'Tens Cihazı, fiziksel rahatsızlıkları hafifletmek için tasarlanmış profesyonel TENS/EMS cihazıdır....',
  22900,
  NULL,
  10,
  '["/images/products/ev-gerecleri.jpg"]'::jsonb,
  '["12 tedavi modu","LCD ekran","Ayarlanabilir yoğunluk","Zamanlayıcı","Pil/USB güç","1 yıl garanti"]'::jsonb,
  '{"Marka":"Aquails","Kategori":"Tens Cihazı","Garanti":"2 Yıl"}'::jsonb,
  4.2,
  14,
  NULL,
  NULL,
  true
) ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  category_id = EXCLUDED.category_id,
  description = EXCLUDED.description,
  short_description = EXCLUDED.short_description,
  price = EXCLUDED.price,
  old_price = EXCLUDED.old_price,
  stock = EXCLUDED.stock,
  images = EXCLUDED.images,
  features = EXCLUDED.features,
  specifications = EXCLUDED.specifications,
  rating = EXCLUDED.rating,
  review_count = EXCLUDED.review_count,
  badge = EXCLUDED.badge,
  discount_percent = EXCLUDED.discount_percent,
  is_active = true;

INSERT INTO public.products (
  id, name, slug, sku, category_id, description, short_description,
  price, old_price, stock, images, features, specifications,
  rating, review_count, badge, discount_percent, is_active
) VALUES (
  '33333333-3333-3333-3333-00002ac63568',
  '7 PARÇA GRANİT TENCERE SETİ',
  '7-parca-granit-tencere-seti',
  '8055184064557',
  '11111111-1111-1111-1111-111111111113',
  '7 PARÇA GRANİT TENCERE SETİ, mutfağınızda kalite ve şıklığı bir araya getiren dayanıklı ev gerecidir.',
  '7 PARÇA GRANİT TENCERE SETİ, mutfağınızda kalite ve şıklığı bir araya getiren dayanıklı ev gerecidir....',
  22400,
  NULL,
  10,
  '["/images/products/ev-gerecleri.jpg"]'::jsonb,
  '["Dayanıklı döküm/granit","PFOA içermez","Kolay temizlik","Isıya dayanıklı","Şık tasarım","2 yıl garanti"]'::jsonb,
  '{"Marka":"Aquails","Kategori":"Ev Gereçleri","Garanti":"2 Yıl"}'::jsonb,
  4.8,
  102,
  NULL,
  NULL,
  true
) ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  category_id = EXCLUDED.category_id,
  description = EXCLUDED.description,
  short_description = EXCLUDED.short_description,
  price = EXCLUDED.price,
  old_price = EXCLUDED.old_price,
  stock = EXCLUDED.stock,
  images = EXCLUDED.images,
  features = EXCLUDED.features,
  specifications = EXCLUDED.specifications,
  rating = EXCLUDED.rating,
  review_count = EXCLUDED.review_count,
  badge = EXCLUDED.badge,
  discount_percent = EXCLUDED.discount_percent,
  is_active = true;

INSERT INTO public.products (
  id, name, slug, sku, category_id, description, short_description,
  price, old_price, stock, images, features, specifications,
  rating, review_count, badge, discount_percent, is_active
) VALUES (
  '33333333-3333-3333-3333-000057df3605',
  '7 PARÇA DÖKÜM TENCERE SETİ',
  '7-parca-dokum-tencere-seti',
  '8055183114285',
  '11111111-1111-1111-1111-111111111113',
  '7 PARÇA DÖKÜM TENCERE SETİ, mutfağınızda kalite ve şıklığı bir araya getiren dayanıklı ev gerecidir.',
  '7 PARÇA DÖKÜM TENCERE SETİ, mutfağınızda kalite ve şıklığı bir araya getiren dayanıklı ev gerecidir....',
  24800,
  NULL,
  10,
  '["/images/products/ev-gerecleri.jpg"]'::jsonb,
  '["Dayanıklı döküm/granit","PFOA içermez","Kolay temizlik","Isıya dayanıklı","Şık tasarım","2 yıl garanti"]'::jsonb,
  '{"Marka":"Aquails","Kategori":"Ev Gereçleri","Garanti":"2 Yıl"}'::jsonb,
  4.3,
  141,
  NULL,
  NULL,
  true
) ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  category_id = EXCLUDED.category_id,
  description = EXCLUDED.description,
  short_description = EXCLUDED.short_description,
  price = EXCLUDED.price,
  old_price = EXCLUDED.old_price,
  stock = EXCLUDED.stock,
  images = EXCLUDED.images,
  features = EXCLUDED.features,
  specifications = EXCLUDED.specifications,
  rating = EXCLUDED.rating,
  review_count = EXCLUDED.review_count,
  badge = EXCLUDED.badge,
  discount_percent = EXCLUDED.discount_percent,
  is_active = true;

INSERT INTO public.products (
  id, name, slug, sku, category_id, description, short_description,
  price, old_price, stock, images, features, specifications,
  rating, review_count, badge, discount_percent, is_active
) VALUES (
  '33333333-3333-3333-3333-000059b88924',
  '6 PARÇA DÖKÜM TENCERE SETİ',
  '6-parca-dokum-tencere-seti',
  '8055182524461',
  '11111111-1111-1111-1111-111111111113',
  '6 PARÇA DÖKÜM TENCERE SETİ, mutfağınızda kalite ve şıklığı bir araya getiren dayanıklı ev gerecidir.',
  '6 PARÇA DÖKÜM TENCERE SETİ, mutfağınızda kalite ve şıklığı bir araya getiren dayanıklı ev gerecidir....',
  16800,
  NULL,
  10,
  '["/images/products/sebiller.jpg"]'::jsonb,
  '["Dayanıklı döküm/granit","PFOA içermez","Kolay temizlik","Isıya dayanıklı","Şık tasarım","2 yıl garanti"]'::jsonb,
  '{"Marka":"Aquails","Kategori":"Ev Gereçleri","Garanti":"2 Yıl"}'::jsonb,
  4.6,
  142,
  NULL,
  NULL,
  true
) ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  category_id = EXCLUDED.category_id,
  description = EXCLUDED.description,
  short_description = EXCLUDED.short_description,
  price = EXCLUDED.price,
  old_price = EXCLUDED.old_price,
  stock = EXCLUDED.stock,
  images = EXCLUDED.images,
  features = EXCLUDED.features,
  specifications = EXCLUDED.specifications,
  rating = EXCLUDED.rating,
  review_count = EXCLUDED.review_count,
  badge = EXCLUDED.badge,
  discount_percent = EXCLUDED.discount_percent,
  is_active = true;

INSERT INTO public.products (
  id, name, slug, sku, category_id, description, short_description,
  price, old_price, stock, images, features, specifications,
  rating, review_count, badge, discount_percent, is_active
) VALUES (
  '33333333-3333-3333-3333-00005fa05b08',
  'Aquails OR-80 Sebil',
  'or-80-sebil',
  '8053277425709',
  '11111111-1111-1111-1111-111111111104',
  'OR-80 Sebil, sıcak ve soğuk su seçenekleriyle ofis ve ev kullanımına uygun arıtmalı sebil sistemidir.',
  'OR-80 Sebil, sıcak ve soğuk su seçenekleriyle ofis ve ev kullanımına uygun arıtmalı sebil sistemidir....',
  155000,
  NULL,
  10,
  '["/images/products/sebiller.jpg"]'::jsonb,
  '["Sıcak & soğuk su","Arıtmalı sistem","Enerji tasarrufu","Çocuk güvenlik kilidi","Geniş su haznesi","2 yıl garanti"]'::jsonb,
  '{"Marka":"Aquails","Kategori":"Sebiller","Garanti":"2 Yıl"}'::jsonb,
  4.2,
  110,
  NULL,
  NULL,
  true
) ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  category_id = EXCLUDED.category_id,
  description = EXCLUDED.description,
  short_description = EXCLUDED.short_description,
  price = EXCLUDED.price,
  old_price = EXCLUDED.old_price,
  stock = EXCLUDED.stock,
  images = EXCLUDED.images,
  features = EXCLUDED.features,
  specifications = EXCLUDED.specifications,
  rating = EXCLUDED.rating,
  review_count = EXCLUDED.review_count,
  badge = EXCLUDED.badge,
  discount_percent = EXCLUDED.discount_percent,
  is_active = true;

INSERT INTO public.products (
  id, name, slug, sku, category_id, description, short_description,
  price, old_price, stock, images, features, specifications,
  rating, review_count, badge, discount_percent, is_active
) VALUES (
  '33333333-3333-3333-3333-000027fcd46b',
  'Aquails OR-50 Sebil',
  'or-50-sebil',
  '8053277360173',
  '11111111-1111-1111-1111-111111111104',
  'OR-50 Sebil, sıcak ve soğuk su seçenekleriyle ofis ve ev kullanımına uygun arıtmalı sebil sistemidir.',
  'OR-50 Sebil, sıcak ve soğuk su seçenekleriyle ofis ve ev kullanımına uygun arıtmalı sebil sistemidir....',
  135000,
  NULL,
  10,
  '["/images/products/sebiller.jpg"]'::jsonb,
  '["Sıcak & soğuk su","Arıtmalı sistem","Enerji tasarrufu","Çocuk güvenlik kilidi","Geniş su haznesi","2 yıl garanti"]'::jsonb,
  '{"Marka":"Aquails","Kategori":"Sebiller","Garanti":"2 Yıl"}'::jsonb,
  4.9,
  27,
  NULL,
  NULL,
  true
) ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  category_id = EXCLUDED.category_id,
  description = EXCLUDED.description,
  short_description = EXCLUDED.short_description,
  price = EXCLUDED.price,
  old_price = EXCLUDED.old_price,
  stock = EXCLUDED.stock,
  images = EXCLUDED.images,
  features = EXCLUDED.features,
  specifications = EXCLUDED.specifications,
  rating = EXCLUDED.rating,
  review_count = EXCLUDED.review_count,
  badge = EXCLUDED.badge,
  discount_percent = EXCLUDED.discount_percent,
  is_active = true;

INSERT INTO public.products (
  id, name, slug, sku, category_id, description, short_description,
  price, old_price, stock, images, features, specifications,
  rating, review_count, badge, discount_percent, is_active
) VALUES (
  '33333333-3333-3333-3333-000038a5e84b',
  'Aquails OR-115 ARITMALI SEBİL',
  'or-115-aritmali-sebil',
  '8053277294637',
  '11111111-1111-1111-1111-111111111104',
  'OR-115 ARITMALI SEBİL, sıcak ve soğuk su seçenekleriyle ofis ve ev kullanımına uygun arıtmalı sebil sistemidir.',
  'OR-115 ARITMALI SEBİL, sıcak ve soğuk su seçenekleriyle ofis ve ev kullanımına uygun arıtmalı sebil sistemidir....',
  138000,
  NULL,
  10,
  '["/images/products/direkt-akis-su-aritma.jpg"]'::jsonb,
  '["Sıcak & soğuk su","Arıtmalı sistem","Enerji tasarrufu","Çocuk güvenlik kilidi","Geniş su haznesi","2 yıl garanti"]'::jsonb,
  '{"Marka":"Aquails","Kategori":"Sebiller","Garanti":"2 Yıl"}'::jsonb,
  4.6,
  70,
  NULL,
  NULL,
  true
) ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  category_id = EXCLUDED.category_id,
  description = EXCLUDED.description,
  short_description = EXCLUDED.short_description,
  price = EXCLUDED.price,
  old_price = EXCLUDED.old_price,
  stock = EXCLUDED.stock,
  images = EXCLUDED.images,
  features = EXCLUDED.features,
  specifications = EXCLUDED.specifications,
  rating = EXCLUDED.rating,
  review_count = EXCLUDED.review_count,
  badge = EXCLUDED.badge,
  discount_percent = EXCLUDED.discount_percent,
  is_active = true;

INSERT INTO public.products (
  id, name, slug, sku, category_id, description, short_description,
  price, old_price, stock, images, features, specifications,
  rating, review_count, badge, discount_percent, is_active
) VALUES (
  '33333333-3333-3333-3333-000075738a47',
  'Aquails WATER CHEF DİREK AKIŞ SU ARITMA CİHAZI',
  'aquails-water-chef-direk-akis-su-aritma-cihazi',
  '8053277229101',
  '11111111-1111-1111-1111-111111111102',
  'Aquails WATER CHEF DİREK AKIŞ SU ARITMA CİHAZI, tank kullanmadan anında saf su üreten son nesil direkt akış su arıtma cihazıdır. Yüksek kapasite, düşük su atığı.',
  'Aquails WATER CHEF DİREK AKIŞ SU ARITMA CİHAZI, tank kullanmadan anında saf su üreten son nesil direkt akış su arıtma ci...',
  95900,
  NULL,
  10,
  '["/images/products/filtreler.jpg"]'::jsonb,
  '["Tankless tasarım","Anında saf su","Günlük 600-800L kapasite","Otomatik yıkama","Düşük su atığı","5 yıl garanti"]'::jsonb,
  '{"Marka":"Aquails","Kategori":"Direkt Akış Su Arıtma","Garanti":"5 Yıl"}'::jsonb,
  4.5,
  105,
  'premium',
  NULL,
  true
) ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  category_id = EXCLUDED.category_id,
  description = EXCLUDED.description,
  short_description = EXCLUDED.short_description,
  price = EXCLUDED.price,
  old_price = EXCLUDED.old_price,
  stock = EXCLUDED.stock,
  images = EXCLUDED.images,
  features = EXCLUDED.features,
  specifications = EXCLUDED.specifications,
  rating = EXCLUDED.rating,
  review_count = EXCLUDED.review_count,
  badge = EXCLUDED.badge,
  discount_percent = EXCLUDED.discount_percent,
  is_active = true;

INSERT INTO public.products (
  id, name, slug, sku, category_id, description, short_description,
  price, old_price, stock, images, features, specifications,
  rating, review_count, badge, discount_percent, is_active
) VALUES (
  '33333333-3333-3333-3333-000014b5fa8a',
  'Water chef filtreler',
  'water-chef-filtreler',
  '8053274771501',
  '11111111-1111-1111-1111-111111111106',
  'Water chef filtreler, Aquails su arıtma cihazlarıyla tam uyumlu, NSF sertifikalı yüksek performanslı filtredir.',
  'Water chef filtreler, Aquails su arıtma cihazlarıyla tam uyumlu, NSF sertifikalı yüksek performanslı filtredir....',
  7900,
  NULL,
  10,
  '["/images/products/sebiller.jpg"]'::jsonb,
  '["NSF sertifikalı","6-12 ay ömür","Kolay değişim","Yüksek filtrasyon verimi","Güvenli paketleme","Aquails uyumlu"]'::jsonb,
  '{"Marka":"Aquails","Kategori":"Filtreler","Garanti":"2 Yıl"}'::jsonb,
  4.3,
  27,
  'premium',
  NULL,
  true
) ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  category_id = EXCLUDED.category_id,
  description = EXCLUDED.description,
  short_description = EXCLUDED.short_description,
  price = EXCLUDED.price,
  old_price = EXCLUDED.old_price,
  stock = EXCLUDED.stock,
  images = EXCLUDED.images,
  features = EXCLUDED.features,
  specifications = EXCLUDED.specifications,
  rating = EXCLUDED.rating,
  review_count = EXCLUDED.review_count,
  badge = EXCLUDED.badge,
  discount_percent = EXCLUDED.discount_percent,
  is_active = true;

INSERT INTO public.products (
  id, name, slug, sku, category_id, description, short_description,
  price, old_price, stock, images, features, specifications,
  rating, review_count, badge, discount_percent, is_active
) VALUES (
  '33333333-3333-3333-3333-00004879eec9',
  'Aquails TANKSIZ SEBİL APARATI',
  'tanksiz-sebil-aparati',
  '8053271625773',
  '11111111-1111-1111-1111-111111111104',
  'TANKSIZ SEBİL APARATI, sıcak ve soğuk su seçenekleriyle ofis ve ev kullanımına uygun arıtmalı sebil sistemidir.',
  'TANKSIZ SEBİL APARATI, sıcak ve soğuk su seçenekleriyle ofis ve ev kullanımına uygun arıtmalı sebil sistemidir....',
  2500,
  NULL,
  10,
  '["/images/products/sebiller.jpg"]'::jsonb,
  '["Sıcak & soğuk su","Arıtmalı sistem","Enerji tasarrufu","Çocuk güvenlik kilidi","Geniş su haznesi","2 yıl garanti"]'::jsonb,
  '{"Marka":"Aquails","Kategori":"Sebiller","Garanti":"2 Yıl"}'::jsonb,
  4.8,
  112,
  NULL,
  NULL,
  true
) ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  category_id = EXCLUDED.category_id,
  description = EXCLUDED.description,
  short_description = EXCLUDED.short_description,
  price = EXCLUDED.price,
  old_price = EXCLUDED.old_price,
  stock = EXCLUDED.stock,
  images = EXCLUDED.images,
  features = EXCLUDED.features,
  specifications = EXCLUDED.specifications,
  rating = EXCLUDED.rating,
  review_count = EXCLUDED.review_count,
  badge = EXCLUDED.badge,
  discount_percent = EXCLUDED.discount_percent,
  is_active = true;

INSERT INTO public.products (
  id, name, slug, sku, category_id, description, short_description,
  price, old_price, stock, images, features, specifications,
  rating, review_count, badge, discount_percent, is_active
) VALUES (
  '33333333-3333-3333-3333-000037ef1bca',
  'Aquails TANKLI SEBİL APARATI',
  'tankli-sebil-aparati',
  '8053271429165',
  '11111111-1111-1111-1111-111111111104',
  'TANKLI SEBİL APARATI, sıcak ve soğuk su seçenekleriyle ofis ve ev kullanımına uygun arıtmalı sebil sistemidir.',
  'TANKLI SEBİL APARATI, sıcak ve soğuk su seçenekleriyle ofis ve ev kullanımına uygun arıtmalı sebil sistemidir....',
  3500,
  NULL,
  10,
  '["/images/products/filtreler.jpg"]'::jsonb,
  '["Sıcak & soğuk su","Arıtmalı sistem","Enerji tasarrufu","Çocuk güvenlik kilidi","Geniş su haznesi","2 yıl garanti"]'::jsonb,
  '{"Marka":"Aquails","Kategori":"Sebiller","Garanti":"2 Yıl"}'::jsonb,
  4.9,
  85,
  NULL,
  NULL,
  true
) ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  category_id = EXCLUDED.category_id,
  description = EXCLUDED.description,
  short_description = EXCLUDED.short_description,
  price = EXCLUDED.price,
  old_price = EXCLUDED.old_price,
  stock = EXCLUDED.stock,
  images = EXCLUDED.images,
  features = EXCLUDED.features,
  specifications = EXCLUDED.specifications,
  rating = EXCLUDED.rating,
  review_count = EXCLUDED.review_count,
  badge = EXCLUDED.badge,
  discount_percent = EXCLUDED.discount_percent,
  is_active = true;

INSERT INTO public.products (
  id, name, slug, sku, category_id, description, short_description,
  price, old_price, stock, images, features, specifications,
  rating, review_count, badge, discount_percent, is_active
) VALUES (
  '33333333-3333-3333-3333-00001b93cdf2',
  'Aquails POST KARBON FİLTRE',
  'aquails-post-karbon-filtre',
  '8053271330861',
  '11111111-1111-1111-1111-111111111106',
  'Aquails POST KARBON FİLTRE, Aquails su arıtma cihazlarıyla tam uyumlu, NSF sertifikalı yüksek performanslı filtredir.',
  'Aquails POST KARBON FİLTRE, Aquails su arıtma cihazlarıyla tam uyumlu, NSF sertifikalı yüksek performanslı filtredir....',
  749,
  950,
  10,
  '["/images/products/direkt-akis-su-aritma.jpg"]'::jsonb,
  '["NSF sertifikalı","6-12 ay ömür","Kolay değişim","Yüksek filtrasyon verimi","Güvenli paketleme","Aquails uyumlu"]'::jsonb,
  '{"Marka":"Aquails","Kategori":"Filtreler","Garanti":"2 Yıl"}'::jsonb,
  4.8,
  54,
  'discount',
  21,
  true
) ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  category_id = EXCLUDED.category_id,
  description = EXCLUDED.description,
  short_description = EXCLUDED.short_description,
  price = EXCLUDED.price,
  old_price = EXCLUDED.old_price,
  stock = EXCLUDED.stock,
  images = EXCLUDED.images,
  features = EXCLUDED.features,
  specifications = EXCLUDED.specifications,
  rating = EXCLUDED.rating,
  review_count = EXCLUDED.review_count,
  badge = EXCLUDED.badge,
  discount_percent = EXCLUDED.discount_percent,
  is_active = true;

INSERT INTO public.products (
  id, name, slug, sku, category_id, description, short_description,
  price, old_price, stock, images, features, specifications,
  rating, review_count, badge, discount_percent, is_active
) VALUES (
  '33333333-3333-3333-3333-00007f496ce8',
  'Aquails AQL-300 / 300 GPD DİREK AKIŞ SU ARITMA CİHAZI',
  'aql-300-300-gpd-direk-akis-su-aritma-cihazi',
  '8053271199789',
  '11111111-1111-1111-1111-111111111102',
  'AQL-300 / 300 GPD DİREK AKIŞ SU ARITMA CİHAZI, tank kullanmadan anında saf su üreten son nesil direkt akış su arıtma cihazıdır. Yüksek kapasite, düşük su atığı.',
  'AQL-300 / 300 GPD DİREK AKIŞ SU ARITMA CİHAZI, tank kullanmadan anında saf su üreten son nesil direkt akış su arıtma cih...',
  84900,
  NULL,
  10,
  '["/images/products/filtreler.jpg"]'::jsonb,
  '["Tankless tasarım","Anında saf su","Günlük 600-800L kapasite","Otomatik yıkama","Düşük su atığı","5 yıl garanti"]'::jsonb,
  '{"Marka":"Aquails","Kategori":"Direkt Akış Su Arıtma","Garanti":"5 Yıl","Membran Kapasitesi":"300 GPD"}'::jsonb,
  4.2,
  110,
  NULL,
  NULL,
  true
) ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  category_id = EXCLUDED.category_id,
  description = EXCLUDED.description,
  short_description = EXCLUDED.short_description,
  price = EXCLUDED.price,
  old_price = EXCLUDED.old_price,
  stock = EXCLUDED.stock,
  images = EXCLUDED.images,
  features = EXCLUDED.features,
  specifications = EXCLUDED.specifications,
  rating = EXCLUDED.rating,
  review_count = EXCLUDED.review_count,
  badge = EXCLUDED.badge,
  discount_percent = EXCLUDED.discount_percent,
  is_active = true;

INSERT INTO public.products (
  id, name, slug, sku, category_id, description, short_description,
  price, old_price, stock, images, features, specifications,
  rating, review_count, badge, discount_percent, is_active
) VALUES (
  '33333333-3333-3333-3333-0000666f367f',
  'Aquails AQL-300 RO',
  'aquails-aql-300-ro',
  '8053270839341',
  '11111111-1111-1111-1111-111111111106',
  'Aquails AQL-300 RO, Aquails su arıtma cihazlarıyla tam uyumlu, NSF sertifikalı yüksek performanslı filtredir.',
  'Aquails AQL-300 RO, Aquails su arıtma cihazlarıyla tam uyumlu, NSF sertifikalı yüksek performanslı filtredir....',
  45999,
  50000,
  10,
  '["/images/products/su-aritma-cihazlari.jpg"]'::jsonb,
  '["NSF sertifikalı","6-12 ay ömür","Kolay değişim","Yüksek filtrasyon verimi","Güvenli paketleme","Aquails uyumlu"]'::jsonb,
  '{"Marka":"Aquails","Kategori":"Filtreler","Garanti":"2 Yıl"}'::jsonb,
  4.2,
  38,
  'discount',
  8,
  true
) ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  category_id = EXCLUDED.category_id,
  description = EXCLUDED.description,
  short_description = EXCLUDED.short_description,
  price = EXCLUDED.price,
  old_price = EXCLUDED.old_price,
  stock = EXCLUDED.stock,
  images = EXCLUDED.images,
  features = EXCLUDED.features,
  specifications = EXCLUDED.specifications,
  rating = EXCLUDED.rating,
  review_count = EXCLUDED.review_count,
  badge = EXCLUDED.badge,
  discount_percent = EXCLUDED.discount_percent,
  is_active = true;

INSERT INTO public.products (
  id, name, slug, sku, category_id, description, short_description,
  price, old_price, stock, images, features, specifications,
  rating, review_count, badge, discount_percent, is_active
) VALUES (
  '33333333-3333-3333-3333-00001c5848e1',
  'Aquails H2O TESLA SU ARITMA SİSTEMİ',
  'aquails-h2o-tesla-su-aritma-sistemi',
  '8053270708269',
  '11111111-1111-1111-1111-111111111101',
  'Aquails H2O TESLA SU ARITMA SİSTEMİ, 7 aşamalı Reverse Osmosis teknolojisi ile musluk suyunuzu en saf hale getiren premium su arıtma sistemidir. %99.9 arıtma performansı.',
  'Aquails H2O TESLA SU ARITMA SİSTEMİ, 7 aşamalı Reverse Osmosis teknolojisi ile musluk suyunuzu en saf hale getiren premi...',
  42000,
  NULL,
  10,
  '["/images/products/su-aritma-cihazlari.jpg"]'::jsonb,
  '["7 aşamalı filtrasyon","Günlük 189L su üretimi","Paslanmaz çelik tank","Enerji verimli","Kolay kurulum","5 yıl garanti"]'::jsonb,
  '{"Marka":"Aquails","Kategori":"Su Arıtma Cihazları","Garanti":"5 Yıl"}'::jsonb,
  4.4,
  82,
  'premium',
  NULL,
  true
) ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  category_id = EXCLUDED.category_id,
  description = EXCLUDED.description,
  short_description = EXCLUDED.short_description,
  price = EXCLUDED.price,
  old_price = EXCLUDED.old_price,
  stock = EXCLUDED.stock,
  images = EXCLUDED.images,
  features = EXCLUDED.features,
  specifications = EXCLUDED.specifications,
  rating = EXCLUDED.rating,
  review_count = EXCLUDED.review_count,
  badge = EXCLUDED.badge,
  discount_percent = EXCLUDED.discount_percent,
  is_active = true;

INSERT INTO public.products (
  id, name, slug, sku, category_id, description, short_description,
  price, old_price, stock, images, features, specifications,
  rating, review_count, badge, discount_percent, is_active
) VALUES (
  '33333333-3333-3333-3333-00000833151e',
  'Aquails H2O NEO SU ARITMA SİSTEMİ',
  'aquails-h2o-neo-su-aritma-sistemi',
  '8053270577197',
  '11111111-1111-1111-1111-111111111101',
  'Aquails H2O NEO SU ARITMA SİSTEMİ, 7 aşamalı Reverse Osmosis teknolojisi ile musluk suyunuzu en saf hale getiren premium su arıtma sistemidir. %99.9 arıtma performansı.',
  'Aquails H2O NEO SU ARITMA SİSTEMİ, 7 aşamalı Reverse Osmosis teknolojisi ile musluk suyunuzu en saf hale getiren premium...',
  29990,
  NULL,
  10,
  '["/images/products/bina-girisi-filtrasyon.jpg"]'::jsonb,
  '["7 aşamalı filtrasyon","Günlük 189L su üretimi","Paslanmaz çelik tank","Enerji verimli","Kolay kurulum","5 yıl garanti"]'::jsonb,
  '{"Marka":"Aquails","Kategori":"Su Arıtma Cihazları","Garanti":"5 Yıl"}'::jsonb,
  4.8,
  64,
  'new',
  NULL,
  true
) ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  category_id = EXCLUDED.category_id,
  description = EXCLUDED.description,
  short_description = EXCLUDED.short_description,
  price = EXCLUDED.price,
  old_price = EXCLUDED.old_price,
  stock = EXCLUDED.stock,
  images = EXCLUDED.images,
  features = EXCLUDED.features,
  specifications = EXCLUDED.specifications,
  rating = EXCLUDED.rating,
  review_count = EXCLUDED.review_count,
  badge = EXCLUDED.badge,
  discount_percent = EXCLUDED.discount_percent,
  is_active = true;

INSERT INTO public.products (
  id, name, slug, sku, category_id, description, short_description,
  price, old_price, stock, images, features, specifications,
  rating, review_count, badge, discount_percent, is_active
) VALUES (
  '33333333-3333-3333-3333-00006451f6ea',
  'Aquails 10" 3 LÜ BİNA GİRİŞ FİLTRASYON ARITMA SİSTEMİ',
  'aquails-10-3-lu-bina-giris-filtrasyon-aritma-sistemi',
  '8053270249517',
  '11111111-1111-1111-1111-111111111105',
  'Aquails 10" 3 LÜ BİNA GİRİŞ FİLTRASYON ARITMA SİSTEMİ, apartman ve site girişlerinde kullanılan profesyonel ön filtrasyon sistemidir.',
  'Aquails 10" 3 LÜ BİNA GİRİŞ FİLTRASYON ARITMA SİSTEMİ, apartman ve site girişlerinde kullanılan profesyonel ön filtrasyo...',
  27900,
  NULL,
  10,
  '["/images/products/su-aritma-cihazlari.jpg"]'::jsonb,
  '["20 inç jumbo filtreler","Paslanmaz çelik başlık","Yüksek debi","Kolay filtre değişimi","Paslanmaz bağlantı","2 yıl garanti"]'::jsonb,
  '{"Marka":"Aquails","Kategori":"Bina Girişi Filtrasyon","Garanti":"2 Yıl","Aşama Sayısı":"3 Aşama"}'::jsonb,
  4.2,
  128,
  NULL,
  NULL,
  true
) ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  category_id = EXCLUDED.category_id,
  description = EXCLUDED.description,
  short_description = EXCLUDED.short_description,
  price = EXCLUDED.price,
  old_price = EXCLUDED.old_price,
  stock = EXCLUDED.stock,
  images = EXCLUDED.images,
  features = EXCLUDED.features,
  specifications = EXCLUDED.specifications,
  rating = EXCLUDED.rating,
  review_count = EXCLUDED.review_count,
  badge = EXCLUDED.badge,
  discount_percent = EXCLUDED.discount_percent,
  is_active = true;

INSERT INTO public.products (
  id, name, slug, sku, category_id, description, short_description,
  price, old_price, stock, images, features, specifications,
  rating, review_count, badge, discount_percent, is_active
) VALUES (
  '33333333-3333-3333-3333-000059920b90',
  'Aquails H2O GREEN PLUS SU ARITMA SİSTEMİ',
  'aquails-h2o-green-plus-su-aritma-sistemi',
  '8053270020141',
  '11111111-1111-1111-1111-111111111101',
  'Aquails H2O GREEN PLUS SU ARITMA SİSTEMİ, 7 aşamalı Reverse Osmosis teknolojisi ile musluk suyunuzu en saf hale getiren premium su arıtma sistemidir. %99.9 arıtma performansı.',
  'Aquails H2O GREEN PLUS SU ARITMA SİSTEMİ, 7 aşamalı Reverse Osmosis teknolojisi ile musluk suyunuzu en saf hale getiren ...',
  28800,
  NULL,
  10,
  '["/images/products/su-aritma-cihazlari.jpg"]'::jsonb,
  '["7 aşamalı filtrasyon","Günlük 189L su üretimi","Paslanmaz çelik tank","Enerji verimli","Kolay kurulum","5 yıl garanti"]'::jsonb,
  '{"Marka":"Aquails","Kategori":"Su Arıtma Cihazları","Garanti":"5 Yıl"}'::jsonb,
  4.2,
  110,
  'premium',
  NULL,
  true
) ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  category_id = EXCLUDED.category_id,
  description = EXCLUDED.description,
  short_description = EXCLUDED.short_description,
  price = EXCLUDED.price,
  old_price = EXCLUDED.old_price,
  stock = EXCLUDED.stock,
  images = EXCLUDED.images,
  features = EXCLUDED.features,
  specifications = EXCLUDED.specifications,
  rating = EXCLUDED.rating,
  review_count = EXCLUDED.review_count,
  badge = EXCLUDED.badge,
  discount_percent = EXCLUDED.discount_percent,
  is_active = true;

INSERT INTO public.products (
  id, name, slug, sku, category_id, description, short_description,
  price, old_price, stock, images, features, specifications,
  rating, review_count, badge, discount_percent, is_active
) VALUES (
  '33333333-3333-3333-3333-000042d4443e',
  'Aquails H2O DROP PLUS SU ARITMA SİSTEMİ',
  'aquails-h2o-drop-plus-su-aritma-sistemi',
  '8053269823533',
  '11111111-1111-1111-1111-111111111101',
  'Aquails H2O DROP PLUS SU ARITMA SİSTEMİ, 7 aşamalı Reverse Osmosis teknolojisi ile musluk suyunuzu en saf hale getiren premium su arıtma sistemidir. %99.9 arıtma performansı.',
  'Aquails H2O DROP PLUS SU ARITMA SİSTEMİ, 7 aşamalı Reverse Osmosis teknolojisi ile musluk suyunuzu en saf hale getiren p...',
  23790,
  NULL,
  10,
  '["/images/products/su-aritma-cihazlari.jpg"]'::jsonb,
  '["7 aşamalı filtrasyon","Günlük 189L su üretimi","Paslanmaz çelik tank","Enerji verimli","Kolay kurulum","5 yıl garanti"]'::jsonb,
  '{"Marka":"Aquails","Kategori":"Su Arıtma Cihazları","Garanti":"5 Yıl"}'::jsonb,
  4.7,
  123,
  NULL,
  NULL,
  true
) ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  category_id = EXCLUDED.category_id,
  description = EXCLUDED.description,
  short_description = EXCLUDED.short_description,
  price = EXCLUDED.price,
  old_price = EXCLUDED.old_price,
  stock = EXCLUDED.stock,
  images = EXCLUDED.images,
  features = EXCLUDED.features,
  specifications = EXCLUDED.specifications,
  rating = EXCLUDED.rating,
  review_count = EXCLUDED.review_count,
  badge = EXCLUDED.badge,
  discount_percent = EXCLUDED.discount_percent,
  is_active = true;

INSERT INTO public.products (
  id, name, slug, sku, category_id, description, short_description,
  price, old_price, stock, images, features, specifications,
  rating, review_count, badge, discount_percent, is_active
) VALUES (
  '33333333-3333-3333-3333-0000515c205b',
  'Aquails H2O DROP SU ARITMA SİSTEMİ',
  'aquails-h2o-drop-su-aritma-sistemi',
  '8053269626925',
  '11111111-1111-1111-1111-111111111101',
  'Aquails H2O DROP SU ARITMA SİSTEMİ, 7 aşamalı Reverse Osmosis teknolojisi ile musluk suyunuzu en saf hale getiren premium su arıtma sistemidir. %99.9 arıtma performansı.',
  'Aquails H2O DROP SU ARITMA SİSTEMİ, 7 aşamalı Reverse Osmosis teknolojisi ile musluk suyunuzu en saf hale getiren premiu...',
  19790,
  NULL,
  10,
  '["/images/products/musluklar.jpg"]'::jsonb,
  '["7 aşamalı filtrasyon","Günlük 189L su üretimi","Paslanmaz çelik tank","Enerji verimli","Kolay kurulum","5 yıl garanti"]'::jsonb,
  '{"Marka":"Aquails","Kategori":"Su Arıtma Cihazları","Garanti":"5 Yıl"}'::jsonb,
  4.8,
  112,
  NULL,
  NULL,
  true
) ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  category_id = EXCLUDED.category_id,
  description = EXCLUDED.description,
  short_description = EXCLUDED.short_description,
  price = EXCLUDED.price,
  old_price = EXCLUDED.old_price,
  stock = EXCLUDED.stock,
  images = EXCLUDED.images,
  features = EXCLUDED.features,
  specifications = EXCLUDED.specifications,
  rating = EXCLUDED.rating,
  review_count = EXCLUDED.review_count,
  badge = EXCLUDED.badge,
  discount_percent = EXCLUDED.discount_percent,
  is_active = true;

INSERT INTO public.products (
  id, name, slug, sku, category_id, description, short_description,
  price, old_price, stock, images, features, specifications,
  rating, review_count, badge, discount_percent, is_active
) VALUES (
  '33333333-3333-3333-3333-000020c7d096',
  'Aquails 2 / 3 YOLLU MUSLUK BATARYASI',
  'aquails-2-3-yollu-musluk-bataryasi',
  '8053269561389',
  '11111111-1111-1111-1111-111111111108',
  'Aquails 2 / 3 YOLLU MUSLUK BATARYASI, 304 paslanmaz çelikten üretilmiş, su arıtma cihazlarına uygun estetik ve dayanıklı musluktur.',
  'Aquails 2 / 3 YOLLU MUSLUK BATARYASI, 304 paslanmaz çelikten üretilmiş, su arıtma cihazlarına uygun estetik ve dayanıklı...',
  8699,
  NULL,
  10,
  '["/images/products/membran-filtreler.jpg"]'::jsonb,
  '["304 paslanmaz çelik","Paslanmaya dayanıklı","Krom kaplama","Kolay montaj","Modern tasarım","5 yıl garanti"]'::jsonb,
  '{"Marka":"Aquails","Kategori":"Musluklar","Garanti":"5 Yıl"}'::jsonb,
  4.7,
  159,
  NULL,
  NULL,
  true
) ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  category_id = EXCLUDED.category_id,
  description = EXCLUDED.description,
  short_description = EXCLUDED.short_description,
  price = EXCLUDED.price,
  old_price = EXCLUDED.old_price,
  stock = EXCLUDED.stock,
  images = EXCLUDED.images,
  features = EXCLUDED.features,
  specifications = EXCLUDED.specifications,
  rating = EXCLUDED.rating,
  review_count = EXCLUDED.review_count,
  badge = EXCLUDED.badge,
  discount_percent = EXCLUDED.discount_percent,
  is_active = true;

INSERT INTO public.products (
  id, name, slug, sku, category_id, description, short_description,
  price, old_price, stock, images, features, specifications,
  rating, review_count, badge, discount_percent, is_active
) VALUES (
  '33333333-3333-3333-3333-000078f7fce4',
  'Aquails 1812-80GPD MEMBRAN',
  'aquails-1812-80gpd-membran',
  '8053269397549',
  '11111111-1111-1111-1111-111111111107',
  'Aquails 1812-80GPD MEMBRAN, ters ozmoz teknolojisiyle en saf suyu elde etmenizi sağlayan uzun ömürlü membran filtredir.',
  'Aquails 1812-80GPD MEMBRAN, ters ozmoz teknolojisiyle en saf suyu elde etmenizi sağlayan uzun ömürlü membran filtredir....',
  749,
  1379,
  10,
  '["/images/products/direkt-akis-su-aritma.jpg"]'::jsonb,
  '["80-600 GPD kapasite","Ters ozmoz teknolojisi","2-3 yıl ömür","Yük tuz tutma oranı","Kolay montaj","NSF onaylı"]'::jsonb,
  '{"Marka":"Aquails","Kategori":"Membran Filtreler","Garanti":"2 Yıl","Membran Kapasitesi":"80 GPD"}'::jsonb,
  4.9,
  117,
  'discount',
  46,
  true
) ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  category_id = EXCLUDED.category_id,
  description = EXCLUDED.description,
  short_description = EXCLUDED.short_description,
  price = EXCLUDED.price,
  old_price = EXCLUDED.old_price,
  stock = EXCLUDED.stock,
  images = EXCLUDED.images,
  features = EXCLUDED.features,
  specifications = EXCLUDED.specifications,
  rating = EXCLUDED.rating,
  review_count = EXCLUDED.review_count,
  badge = EXCLUDED.badge,
  discount_percent = EXCLUDED.discount_percent,
  is_active = true;

INSERT INTO public.products (
  id, name, slug, sku, category_id, description, short_description,
  price, old_price, stock, images, features, specifications,
  rating, review_count, badge, discount_percent, is_active
) VALUES (
  '33333333-3333-3333-3333-00000ed691ee',
  'Aquails AQL-600 / 600 GPD DİREK AKIŞ SU ARITMA CİHAZI',
  'aql-600-600-gpd-direk-akis-su-aritma-cihazi',
  '8053267136557',
  '11111111-1111-1111-1111-111111111102',
  'AQL-600 / 600 GPD DİREK AKIŞ SU ARITMA CİHAZI, tank kullanmadan anında saf su üreten son nesil direkt akış su arıtma cihazıdır. Yüksek kapasite, düşük su atığı.',
  'AQL-600 / 600 GPD DİREK AKIŞ SU ARITMA CİHAZI, tank kullanmadan anında saf su üreten son nesil direkt akış su arıtma cih...',
  99000,
  NULL,
  10,
  '["/images/products/filtreler.jpg"]'::jsonb,
  '["Tankless tasarım","Anında saf su","Günlük 600-800L kapasite","Otomatik yıkama","Düşük su atığı","5 yıl garanti"]'::jsonb,
  '{"Marka":"Aquails","Kategori":"Direkt Akış Su Arıtma","Garanti":"5 Yıl","Membran Kapasitesi":"600 GPD"}'::jsonb,
  4.3,
  91,
  NULL,
  NULL,
  true
) ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  category_id = EXCLUDED.category_id,
  description = EXCLUDED.description,
  short_description = EXCLUDED.short_description,
  price = EXCLUDED.price,
  old_price = EXCLUDED.old_price,
  stock = EXCLUDED.stock,
  images = EXCLUDED.images,
  features = EXCLUDED.features,
  specifications = EXCLUDED.specifications,
  rating = EXCLUDED.rating,
  review_count = EXCLUDED.review_count,
  badge = EXCLUDED.badge,
  discount_percent = EXCLUDED.discount_percent,
  is_active = true;

INSERT INTO public.products (
  id, name, slug, sku, category_id, description, short_description,
  price, old_price, stock, images, features, specifications,
  rating, review_count, badge, discount_percent, is_active
) VALUES (
  '33333333-3333-3333-3333-000053b0a18a',
  'Aquails AQL-150 Softmax Maxi',
  'aql-150-softmax-maxi',
  '8053266972717',
  '11111111-1111-1111-1111-111111111106',
  'Aquails AQL-150 Softmax Maxi, Aquails su arıtma cihazlarıyla tam uyumlu, NSF sertifikalı yüksek performanslı filtredir.',
  'Aquails AQL-150 Softmax Maxi, Aquails su arıtma cihazlarıyla tam uyumlu, NSF sertifikalı yüksek performanslı filtredir....',
  147000,
  NULL,
  10,
  '["/images/products/filtreler.jpg"]'::jsonb,
  '["NSF sertifikalı","6-12 ay ömür","Kolay değişim","Yüksek filtrasyon verimi","Güvenli paketleme","Aquails uyumlu"]'::jsonb,
  '{"Marka":"Aquails","Kategori":"Filtreler","Garanti":"2 Yıl"}'::jsonb,
  4.9,
  101,
  NULL,
  NULL,
  true
) ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  category_id = EXCLUDED.category_id,
  description = EXCLUDED.description,
  short_description = EXCLUDED.short_description,
  price = EXCLUDED.price,
  old_price = EXCLUDED.old_price,
  stock = EXCLUDED.stock,
  images = EXCLUDED.images,
  features = EXCLUDED.features,
  specifications = EXCLUDED.specifications,
  rating = EXCLUDED.rating,
  review_count = EXCLUDED.review_count,
  badge = EXCLUDED.badge,
  discount_percent = EXCLUDED.discount_percent,
  is_active = true;

INSERT INTO public.products (
  id, name, slug, sku, category_id, description, short_description,
  price, old_price, stock, images, features, specifications,
  rating, review_count, badge, discount_percent, is_active
) VALUES (
  '33333333-3333-3333-3333-000034365437',
  'Aquails AQL-100 Soft Midi',
  'aql-100-soft-midi',
  '8053266612269',
  '11111111-1111-1111-1111-111111111106',
  'Aquails AQL-100 Soft Midi, Aquails su arıtma cihazlarıyla tam uyumlu, NSF sertifikalı yüksek performanslı filtredir.',
  'Aquails AQL-100 Soft Midi, Aquails su arıtma cihazlarıyla tam uyumlu, NSF sertifikalı yüksek performanslı filtredir....',
  119900,
  NULL,
  10,
  '["/images/products/filtreler.jpg"]'::jsonb,
  '["NSF sertifikalı","6-12 ay ömür","Kolay değişim","Yüksek filtrasyon verimi","Güvenli paketleme","Aquails uyumlu"]'::jsonb,
  '{"Marka":"Aquails","Kategori":"Filtreler","Garanti":"2 Yıl"}'::jsonb,
  4.5,
  145,
  NULL,
  NULL,
  true
) ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  category_id = EXCLUDED.category_id,
  description = EXCLUDED.description,
  short_description = EXCLUDED.short_description,
  price = EXCLUDED.price,
  old_price = EXCLUDED.old_price,
  stock = EXCLUDED.stock,
  images = EXCLUDED.images,
  features = EXCLUDED.features,
  specifications = EXCLUDED.specifications,
  rating = EXCLUDED.rating,
  review_count = EXCLUDED.review_count,
  badge = EXCLUDED.badge,
  discount_percent = EXCLUDED.discount_percent,
  is_active = true;

INSERT INTO public.products (
  id, name, slug, sku, category_id, description, short_description,
  price, old_price, stock, images, features, specifications,
  rating, review_count, badge, discount_percent, is_active
) VALUES (
  '33333333-3333-3333-3333-0000080ba627',
  'INLINE FİLTRELER',
  'inline-filtreler',
  '8053266382893',
  '11111111-1111-1111-1111-111111111106',
  'INLINE FİLTRELER, Aquails su arıtma cihazlarıyla tam uyumlu, NSF sertifikalı yüksek performanslı filtredir.',
  'INLINE FİLTRELER, Aquails su arıtma cihazlarıyla tam uyumlu, NSF sertifikalı yüksek performanslı filtredir....',
  1349,
  1699,
  10,
  '["/images/products/ev-temizligi.jpg"]'::jsonb,
  '["NSF sertifikalı","6-12 ay ömür","Kolay değişim","Yüksek filtrasyon verimi","Güvenli paketleme","Aquails uyumlu"]'::jsonb,
  '{"Marka":"Aquails","Kategori":"Filtreler","Garanti":"2 Yıl"}'::jsonb,
  4.6,
  36,
  'discount',
  21,
  true
) ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  category_id = EXCLUDED.category_id,
  description = EXCLUDED.description,
  short_description = EXCLUDED.short_description,
  price = EXCLUDED.price,
  old_price = EXCLUDED.old_price,
  stock = EXCLUDED.stock,
  images = EXCLUDED.images,
  features = EXCLUDED.features,
  specifications = EXCLUDED.specifications,
  rating = EXCLUDED.rating,
  review_count = EXCLUDED.review_count,
  badge = EXCLUDED.badge,
  discount_percent = EXCLUDED.discount_percent,
  is_active = true;

INSERT INTO public.products (
  id, name, slug, sku, category_id, description, short_description,
  price, old_price, stock, images, features, specifications,
  rating, review_count, badge, discount_percent, is_active
) VALUES (
  '33333333-3333-3333-3333-00007c2c2a62',
  'TORNADO ELEKTRİKLİ SÜPÜRGE',
  'tornado-elektrikli-supurge',
  '8052759920685',
  '11111111-1111-1111-1111-111111111112',
  'TORNADO ELEKTRİKLİ SÜPÜRGE, evinizi hijyenik tutmanızı sağlayan güçlü performanslı temizlik ürünüdür.',
  'TORNADO ELEKTRİKLİ SÜPÜRGE, evinizi hijyenik tutmanızı sağlayan güçlü performanslı temizlik ürünüdür....',
  38900,
  NULL,
  10,
  '["/images/products/ev-temizligi.jpg"]'::jsonb,
  '["Güçlü emiş","HEPA filtre","Enerji verimli","Sessiz çalışma","Kolay temizlik","2 yıl garanti"]'::jsonb,
  '{"Marka":"Aquails","Kategori":"Ev Temizliği","Garanti":"2 Yıl"}'::jsonb,
  4.7,
  137,
  NULL,
  NULL,
  true
) ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  category_id = EXCLUDED.category_id,
  description = EXCLUDED.description,
  short_description = EXCLUDED.short_description,
  price = EXCLUDED.price,
  old_price = EXCLUDED.old_price,
  stock = EXCLUDED.stock,
  images = EXCLUDED.images,
  features = EXCLUDED.features,
  specifications = EXCLUDED.specifications,
  rating = EXCLUDED.rating,
  review_count = EXCLUDED.review_count,
  badge = EXCLUDED.badge,
  discount_percent = EXCLUDED.discount_percent,
  is_active = true;

INSERT INTO public.products (
  id, name, slug, sku, category_id, description, short_description,
  price, old_price, stock, images, features, specifications,
  rating, review_count, badge, discount_percent, is_active
) VALUES (
  '33333333-3333-3333-3333-000068154153',
  'PRATİK SÜPÜRGE',
  'pratik-supurge',
  '8052759298093',
  '11111111-1111-1111-1111-111111111112',
  'PRATİK SÜPÜRGE, evinizi hijyenik tutmanızı sağlayan güçlü performanslı temizlik ürünüdür.',
  'PRATİK SÜPÜRGE, evinizi hijyenik tutmanızı sağlayan güçlü performanslı temizlik ürünüdür....',
  16200,
  NULL,
  10,
  '["/images/products/ev-gerecleri.jpg"]'::jsonb,
  '["Güçlü emiş","HEPA filtre","Enerji verimli","Sessiz çalışma","Kolay temizlik","2 yıl garanti"]'::jsonb,
  '{"Marka":"Aquails","Kategori":"Ev Temizliği","Garanti":"2 Yıl"}'::jsonb,
  4.6,
  48,
  NULL,
  NULL,
  true
) ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  category_id = EXCLUDED.category_id,
  description = EXCLUDED.description,
  short_description = EXCLUDED.short_description,
  price = EXCLUDED.price,
  old_price = EXCLUDED.old_price,
  stock = EXCLUDED.stock,
  images = EXCLUDED.images,
  features = EXCLUDED.features,
  specifications = EXCLUDED.specifications,
  rating = EXCLUDED.rating,
  review_count = EXCLUDED.review_count,
  badge = EXCLUDED.badge,
  discount_percent = EXCLUDED.discount_percent,
  is_active = true;

INSERT INTO public.products (
  id, name, slug, sku, category_id, description, short_description,
  price, old_price, stock, images, features, specifications,
  rating, review_count, badge, discount_percent, is_active
) VALUES (
  '33333333-3333-3333-3333-000066e8b8a2',
  '89 PARÇA ÇATAL KAŞIK BIÇAK TAKIMI',
  '89-parca-catal-kasik-bicak-takimi',
  '8052755628077',
  '11111111-1111-1111-1111-111111111113',
  '89 PARÇA ÇATAL KAŞIK BIÇAK TAKIMI, mutfağınızda kalite ve şıklığı bir araya getiren dayanıklı ev gerecidir.',
  '89 PARÇA ÇATAL KAŞIK BIÇAK TAKIMI, mutfağınızda kalite ve şıklığı bir araya getiren dayanıklı ev gerecidir....',
  38900,
  NULL,
  10,
  '["/images/products/ev-temizligi.jpg"]'::jsonb,
  '["Dayanıklı döküm/granit","PFOA içermez","Kolay temizlik","Isıya dayanıklı","Şık tasarım","2 yıl garanti"]'::jsonb,
  '{"Marka":"Aquails","Kategori":"Ev Gereçleri","Garanti":"2 Yıl"}'::jsonb,
  4.9,
  125,
  NULL,
  NULL,
  true
) ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  category_id = EXCLUDED.category_id,
  description = EXCLUDED.description,
  short_description = EXCLUDED.short_description,
  price = EXCLUDED.price,
  old_price = EXCLUDED.old_price,
  stock = EXCLUDED.stock,
  images = EXCLUDED.images,
  features = EXCLUDED.features,
  specifications = EXCLUDED.specifications,
  rating = EXCLUDED.rating,
  review_count = EXCLUDED.review_count,
  badge = EXCLUDED.badge,
  discount_percent = EXCLUDED.discount_percent,
  is_active = true;

INSERT INTO public.products (
  id, name, slug, sku, category_id, description, short_description,
  price, old_price, stock, images, features, specifications,
  rating, review_count, badge, discount_percent, is_active
) VALUES (
  '33333333-3333-3333-3333-000038236fda',
  'ELEKTRİKLİ SÜPÜRGE',
  'elektrikli-supurge',
  '8052754186285',
  '11111111-1111-1111-1111-111111111112',
  'ELEKTRİKLİ SÜPÜRGE, evinizi hijyenik tutmanızı sağlayan güçlü performanslı temizlik ürünüdür.',
  'ELEKTRİKLİ SÜPÜRGE, evinizi hijyenik tutmanızı sağlayan güçlü performanslı temizlik ürünüdür....',
  25400,
  NULL,
  10,
  '["/images/products/elektrikli-ev-aletleri.jpg"]'::jsonb,
  '["Güçlü emiş","HEPA filtre","Enerji verimli","Sessiz çalışma","Kolay temizlik","2 yıl garanti"]'::jsonb,
  '{"Marka":"Aquails","Kategori":"Ev Temizliği","Garanti":"2 Yıl"}'::jsonb,
  4.6,
  64,
  NULL,
  NULL,
  true
) ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  category_id = EXCLUDED.category_id,
  description = EXCLUDED.description,
  short_description = EXCLUDED.short_description,
  price = EXCLUDED.price,
  old_price = EXCLUDED.old_price,
  stock = EXCLUDED.stock,
  images = EXCLUDED.images,
  features = EXCLUDED.features,
  specifications = EXCLUDED.specifications,
  rating = EXCLUDED.rating,
  review_count = EXCLUDED.review_count,
  badge = EXCLUDED.badge,
  discount_percent = EXCLUDED.discount_percent,
  is_active = true;

INSERT INTO public.products (
  id, name, slug, sku, category_id, description, short_description,
  price, old_price, stock, images, features, specifications,
  rating, review_count, badge, discount_percent, is_active
) VALUES (
  '33333333-3333-3333-3333-00007b1f2c7e',
  'MİNİ FIRIN',
  'mini-firin',
  '8052752056365',
  '11111111-1111-1111-1111-111111111111',
  'MİNİ FIRIN, mutfak işlerinizi kolaylaştıran güçlü ve enerji verimli elektrikli ev aletidir.',
  'MİNİ FIRIN, mutfak işlerinizi kolaylaştıran güçlü ve enerji verimli elektrikli ev aletidir....',
  21600,
  NULL,
  10,
  '["/images/products/elektrikli-ev-aletleri.jpg"]'::jsonb,
  '["Güçlü motor","Enerji verimli","Paslanmaz çelik bıçaklar","Kolay temizlik","Güvenlik kilidi","2 yıl garanti"]'::jsonb,
  '{"Marka":"Aquails","Kategori":"Elektrikli Ev Aletleri","Garanti":"2 Yıl"}'::jsonb,
  4.3,
  45,
  NULL,
  NULL,
  true
) ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  category_id = EXCLUDED.category_id,
  description = EXCLUDED.description,
  short_description = EXCLUDED.short_description,
  price = EXCLUDED.price,
  old_price = EXCLUDED.old_price,
  stock = EXCLUDED.stock,
  images = EXCLUDED.images,
  features = EXCLUDED.features,
  specifications = EXCLUDED.specifications,
  rating = EXCLUDED.rating,
  review_count = EXCLUDED.review_count,
  badge = EXCLUDED.badge,
  discount_percent = EXCLUDED.discount_percent,
  is_active = true;

INSERT INTO public.products (
  id, name, slug, sku, category_id, description, short_description,
  price, old_price, stock, images, features, specifications,
  rating, review_count, badge, discount_percent, is_active
) VALUES (
  '33333333-3333-3333-3333-0000101effd0',
  'TOST MAKİNESİ',
  'tost-makinesi',
  '8052750549037',
  '11111111-1111-1111-1111-111111111111',
  'TOST MAKİNESİ, mutfak işlerinizi kolaylaştıran güçlü ve enerji verimli elektrikli ev aletidir.',
  'TOST MAKİNESİ, mutfak işlerinizi kolaylaştıran güçlü ve enerji verimli elektrikli ev aletidir....',
  21600,
  NULL,
  10,
  '["/images/products/ev-temizligi.jpg"]'::jsonb,
  '["Güçlü motor","Enerji verimli","Paslanmaz çelik bıçaklar","Kolay temizlik","Güvenlik kilidi","2 yıl garanti"]'::jsonb,
  '{"Marka":"Aquails","Kategori":"Elektrikli Ev Aletleri","Garanti":"2 Yıl"}'::jsonb,
  4.2,
  106,
  NULL,
  NULL,
  true
) ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  category_id = EXCLUDED.category_id,
  description = EXCLUDED.description,
  short_description = EXCLUDED.short_description,
  price = EXCLUDED.price,
  old_price = EXCLUDED.old_price,
  stock = EXCLUDED.stock,
  images = EXCLUDED.images,
  features = EXCLUDED.features,
  specifications = EXCLUDED.specifications,
  rating = EXCLUDED.rating,
  review_count = EXCLUDED.review_count,
  badge = EXCLUDED.badge,
  discount_percent = EXCLUDED.discount_percent,
  is_active = true;

INSERT INTO public.products (
  id, name, slug, sku, category_id, description, short_description,
  price, old_price, stock, images, features, specifications,
  rating, review_count, badge, discount_percent, is_active
) VALUES (
  '33333333-3333-3333-3333-000068154153',
  'PRATİK SÜPÜRGE',
  'pratik-supurge',
  '8052759298093',
  '11111111-1111-1111-1111-111111111112',
  'PRATİK SÜPÜRGE, evinizi hijyenik ve temiz tutmanızı sağlayan, güçlü performanslı elektrikli temizlik ürünüdür.',
  'PRATİK SÜPÜRGE, evinizi hijyenik ve temiz tutmanızı sağlayan, güçlü performanslı elektrikli temizlik ürünüdür....',
  16200,
  NULL,
  10,
  '["/images/products/ev-gerecleri.jpg"]'::jsonb,
  '["Güçlü emiş","HEPA filtre","Enerji verimli","Sessiz çalışma","Kolay temizlik","2 yıl garanti"]'::jsonb,
  '{"Marka":"Aquails","Kategori":"Ev Temizliği","Garanti":"2 Yıl"}'::jsonb,
  4.6,
  48,
  NULL,
  NULL,
  true
) ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  category_id = EXCLUDED.category_id,
  description = EXCLUDED.description,
  short_description = EXCLUDED.short_description,
  price = EXCLUDED.price,
  old_price = EXCLUDED.old_price,
  stock = EXCLUDED.stock,
  images = EXCLUDED.images,
  features = EXCLUDED.features,
  specifications = EXCLUDED.specifications,
  rating = EXCLUDED.rating,
  review_count = EXCLUDED.review_count,
  badge = EXCLUDED.badge,
  discount_percent = EXCLUDED.discount_percent,
  is_active = true;

INSERT INTO public.products (
  id, name, slug, sku, category_id, description, short_description,
  price, old_price, stock, images, features, specifications,
  rating, review_count, badge, discount_percent, is_active
) VALUES (
  '33333333-3333-3333-3333-000066e8b8a2',
  '89 PARÇA ÇATAL KAŞIK BIÇAK TAKIMI',
  '89-parca-catal-kasik-bicak-takimi',
  '8052755628077',
  '11111111-1111-1111-1111-111111111113',
  '89 PARÇA ÇATAL KAŞIK BIÇAK TAKIMI, mutfağınızda kalite ve şıklığı bir araya getiren, dayanıklı malzemeden üretilmiş ev gerecidir.',
  '89 PARÇA ÇATAL KAŞIK BIÇAK TAKIMI, mutfağınızda kalite ve şıklığı bir araya getiren, dayanıklı malzemeden üretilmiş ev g...',
  38900,
  NULL,
  10,
  '["/images/products/ev-temizligi.jpg"]'::jsonb,
  '["Dayanıklı döküm/granit","PFOA içermez","Kolay temizlik","Isıya dayanıklı","Şık tasarım","2 yıl garanti"]'::jsonb,
  '{"Marka":"Aquails","Kategori":"Ev Gereçleri","Garanti":"2 Yıl"}'::jsonb,
  4.9,
  125,
  NULL,
  NULL,
  true
) ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  category_id = EXCLUDED.category_id,
  description = EXCLUDED.description,
  short_description = EXCLUDED.short_description,
  price = EXCLUDED.price,
  old_price = EXCLUDED.old_price,
  stock = EXCLUDED.stock,
  images = EXCLUDED.images,
  features = EXCLUDED.features,
  specifications = EXCLUDED.specifications,
  rating = EXCLUDED.rating,
  review_count = EXCLUDED.review_count,
  badge = EXCLUDED.badge,
  discount_percent = EXCLUDED.discount_percent,
  is_active = true;

INSERT INTO public.products (
  id, name, slug, sku, category_id, description, short_description,
  price, old_price, stock, images, features, specifications,
  rating, review_count, badge, discount_percent, is_active
) VALUES (
  '33333333-3333-3333-3333-000038236fda',
  'ELEKTRİKLİ SÜPÜRGE',
  'elektrikli-supurge',
  '8052754186285',
  '11111111-1111-1111-1111-111111111112',
  'ELEKTRİKLİ SÜPÜRGE, evinizi hijyenik ve temiz tutmanızı sağlayan, güçlü performanslı elektrikli temizlik ürünüdür.',
  'ELEKTRİKLİ SÜPÜRGE, evinizi hijyenik ve temiz tutmanızı sağlayan, güçlü performanslı elektrikli temizlik ürünüdür....',
  25400,
  NULL,
  10,
  '["/images/products/elektrikli-ev-aletleri.jpg"]'::jsonb,
  '["Güçlü emiş","HEPA filtre","Enerji verimli","Sessiz çalışma","Kolay temizlik","2 yıl garanti"]'::jsonb,
  '{"Marka":"Aquails","Kategori":"Ev Temizliği","Garanti":"2 Yıl"}'::jsonb,
  4.6,
  64,
  NULL,
  NULL,
  true
) ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  category_id = EXCLUDED.category_id,
  description = EXCLUDED.description,
  short_description = EXCLUDED.short_description,
  price = EXCLUDED.price,
  old_price = EXCLUDED.old_price,
  stock = EXCLUDED.stock,
  images = EXCLUDED.images,
  features = EXCLUDED.features,
  specifications = EXCLUDED.specifications,
  rating = EXCLUDED.rating,
  review_count = EXCLUDED.review_count,
  badge = EXCLUDED.badge,
  discount_percent = EXCLUDED.discount_percent,
  is_active = true;

INSERT INTO public.products (
  id, name, slug, sku, category_id, description, short_description,
  price, old_price, stock, images, features, specifications,
  rating, review_count, badge, discount_percent, is_active
) VALUES (
  '33333333-3333-3333-3333-00007b1f2c7e',
  'MİNİ FIRIN',
  'mini-firin',
  '8052752056365',
  '11111111-1111-1111-1111-111111111111',
  'MİNİ FIRIN, mutfak işlerinizi kolaylaştıran, güçlü ve enerji verimli elektrikli ev aletidir.',
  'MİNİ FIRIN, mutfak işlerinizi kolaylaştıran, güçlü ve enerji verimli elektrikli ev aletidir....',
  21600,
  NULL,
  10,
  '["/images/products/elektrikli-ev-aletleri.jpg"]'::jsonb,
  '["Güçlü motor","Enerji verimli","Paslanmaz çelik bıçaklar","Kolay temizlik","Güvenlik kilidi","2 yıl garanti"]'::jsonb,
  '{"Marka":"Aquails","Kategori":"Elektrikli Ev Aletleri","Garanti":"2 Yıl"}'::jsonb,
  4.3,
  45,
  NULL,
  NULL,
  true
) ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  category_id = EXCLUDED.category_id,
  description = EXCLUDED.description,
  short_description = EXCLUDED.short_description,
  price = EXCLUDED.price,
  old_price = EXCLUDED.old_price,
  stock = EXCLUDED.stock,
  images = EXCLUDED.images,
  features = EXCLUDED.features,
  specifications = EXCLUDED.specifications,
  rating = EXCLUDED.rating,
  review_count = EXCLUDED.review_count,
  badge = EXCLUDED.badge,
  discount_percent = EXCLUDED.discount_percent,
  is_active = true;

INSERT INTO public.products (
  id, name, slug, sku, category_id, description, short_description,
  price, old_price, stock, images, features, specifications,
  rating, review_count, badge, discount_percent, is_active
) VALUES (
  '33333333-3333-3333-3333-0000101effd0',
  'TOST MAKİNESİ',
  'tost-makinesi',
  '8052750549037',
  '11111111-1111-1111-1111-111111111111',
  'TOST MAKİNESİ, mutfak işlerinizi kolaylaştıran, güçlü ve enerji verimli elektrikli ev aletidir.',
  'TOST MAKİNESİ, mutfak işlerinizi kolaylaştıran, güçlü ve enerji verimli elektrikli ev aletidir....',
  21600,
  NULL,
  10,
  '["/images/products/tost-makinesi-01.jpg","/images/products/tost-makinesi-02.jpg"]'::jsonb,
  '["Güçlü motor","Enerji verimli","Paslanmaz çelik bıçaklar","Kolay temizlik","Güvenlik kilidi","2 yıl garanti"]'::jsonb,
  '{"Marka":"Aquails","Kategori":"Elektrikli Ev Aletleri","Garanti":"2 Yıl"}'::jsonb,
  4.2,
  106,
  NULL,
  NULL,
  true
) ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  category_id = EXCLUDED.category_id,
  description = EXCLUDED.description,
  short_description = EXCLUDED.short_description,
  price = EXCLUDED.price,
  old_price = EXCLUDED.old_price,
  stock = EXCLUDED.stock,
  images = EXCLUDED.images,
  features = EXCLUDED.features,
  specifications = EXCLUDED.specifications,
  rating = EXCLUDED.rating,
  review_count = EXCLUDED.review_count,
  badge = EXCLUDED.badge,
  discount_percent = EXCLUDED.discount_percent,
  is_active = true;
